<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/config/action_filters.xml
// Generated by: AgaviFilterConfigHandler
// Date: 2011-09-02T13:02:10+0000

$filter = new AgaviExecutionTimeFilter();
$filter->initialize($this->context, array (
  'comment' => true,
  'output_types' => 
  array (
    0 => 'html',
  ),
));
$filters[] = $filter;

?>