<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/AppKit/validate/Login/AjaxLogin.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2011-09-02T13:02:13+0000

if($method == 'write') {
${'_validator_username_length'} = new AgaviStringValidator();
${'_validator_username_length'}->initialize($this->getContext(), array (
  'min' => '3',
  'severity' => 'error',
  'required' => false,
  'class' => 'string',
  'name' => 'username_length',
  'max' => '127',
  'base' => NULL,
), array (
  0 => 'username',
), array (
  '' => 'Please provide a username',
  'max' => 'Username is too long',
));
${'validationManager'}->addChild(${'_validator_username_length'});
${'_validator_password_length'} = new AgaviStringValidator();
${'_validator_password_length'}->initialize($this->getContext(), array (
  'min' => '0',
  'severity' => 'error',
  'required' => false,
  'class' => 'string',
  'name' => 'password_length',
  'max' => '80',
  'base' => NULL,
), array (
  0 => 'password',
), array (
  '' => 'Please provide a password',
  'max' => 'Password is too long',
));
${'validationManager'}->addChild(${'_validator_password_length'});
${'_validator_dologin'} = new AgaviNumberValidator();
${'_validator_dologin'}->initialize($this->getContext(), array (
  'type' => 'int',
  'severity' => 'error',
  'required' => false,
  'class' => 'number',
  'name' => 'dologin',
  'base' => NULL,
), array (
  0 => 'dologin',
), array (
  '' => 'Validation of login start failed',
));
${'validationManager'}->addChild(${'_validator_dologin'});
${'_validator_icinga-web-loginname'} = new AgaviStringValidator();
${'_validator_icinga-web-loginname'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => false,
  'class' => 'string',
  'name' => 'icinga-web-loginname',
  'source' => 'cookies',
), array (
  0 => 'icinga-web-loginname',
), array (
));
${'validationManager'}->addChild(${'_validator_icinga-web-loginname'});
}

?>