<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/AppKit/validate/Ext/ApplicationState.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2011-09-02T13:02:12+0000

${'_validator_cmd'} = new AgaviStringValidator();
${'_validator_cmd'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => true,
  'class' => 'string',
  'name' => 'cmd',
  'base' => NULL,
), array (
  0 => 'cmd',
), array (
  '' => 'Command validation failed',
));
${'validationManager'}->addChild(${'_validator_cmd'});
${'_validator_data'} = new AgaviStringValidator();
${'_validator_data'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => true,
  'class' => 'string',
  'name' => 'data',
  'base' => NULL,
), array (
  0 => 'data',
), array (
  '' => 'Data validation failed',
));
${'validationManager'}->addChild(${'_validator_data'});

?>