<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/LConf/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2011-09-02T13:02:09+0000

return array (
  'IcingaLConfBaseAction' => '/usr/local/lconf-standalone/app/modules/LConf/lib/action/IcingaLConfBaseAction.class.php',
  'IcingaLConfBaseModel' => '/usr/local/lconf-standalone/app/modules/LConf/lib/model/IcingaLConfBaseModel.class.php',
  'IcingaLConfBaseView' => '/usr/local/lconf-standalone/app/modules/LConf/lib/view/IcingaLConfBaseView.class.php',
  'LConf_LDAPClientModel' => '/usr/local/lconf-standalone/app/modules/LConf/models/LDAPClientModel.class.php',
  'LconfConnection' => '/usr/local/lconf-standalone/app/modules/LConf/lib/database/LconfConnection.php',
  'LconfDefaultconnection' => '/usr/local/lconf-standalone/app/modules/LConf/lib/database/LconfDefaultconnection.php',
  'LconfFilter' => '/usr/local/lconf-standalone/app/modules/LConf/lib/database/LconfFilter.php',
  'LconfPrincipal' => '/usr/local/lconf-standalone/app/modules/LConf/lib/database/LconfPrincipal.php',
);

?>