<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/Api/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2011-09-02T13:02:09+0000

return array (
  'IcingaApiBaseAction' => '/usr/local/lconf-standalone/app/modules/Api/lib/action/IcingaApiBaseAction.class.php',
  'IcingaApiBaseModel' => '/usr/local/lconf-standalone/app/modules/Api/lib/model/IcingaApiBaseModel.class.php',
  'ApiDataRequestBaseModel' => '/usr/local/lconf-standalone/app/modules/Api/lib/model/ApiDataRequestBaseModel.class.php',
  'AccessConfig' => '/usr/local/lconf-standalone/app/modules/Api/lib/config/AccessConfig.class.php',
  'AccessConfigHandler' => '/usr/local/lconf-standalone/app/modules/Api/lib/config/AccessConfigHandler.class.php',
  'IcingaDoctrineDatabase' => '/usr/local/lconf-standalone/app/modules/Api/lib/database/IcingaDoctrineDatabase.class.php',
  'IcingaDoctrine_Query' => '/usr/local/lconf-standalone/app/modules/Api/lib/database/IcingaDoctrine_Query.class.php',
  'Icinga_Doctrine_Table' => '/usr/local/lconf-standalone/app/modules/Api/lib/database/IcingaDoctrineTable.class.php',
  'IcingaApiBaseView' => '/usr/local/lconf-standalone/app/modules/Api/lib/view/IcingaApiBaseView.class.php',
  'IcingaConsoleInterface' => '/usr/local/lconf-standalone/app/modules/Api/lib/console/IcingaConsoleInterface.php',
  'IcingaConsoleCommandInterface' => '/usr/local/lconf-standalone/app/modules/Api/lib/console/IcingaConsoleCommandInterface.php',
  'BaseConsoleConnection' => '/usr/local/lconf-standalone/app/modules/Api/lib/console/BaseConsoleConnection.class.php',
  'LocalConsoleConnection' => '/usr/local/lconf-standalone/app/modules/Api/lib/console/LocalConsoleConnection.class.php',
  'SshConsoleConnection' => '/usr/local/lconf-standalone/app/modules/Api/lib/console/SshConsoleConnection.class.php',
  'ApiSSHNotInstalledException' => '/usr/local/lconf-standalone/app/modules/Api/lib/console/SshConsoleConnection.class.php',
  'ApiInvalidAuthTypeException' => '/usr/local/lconf-standalone/app/modules/Api/lib/console/SshConsoleConnection.class.php',
  'ApiCommandFailedException' => '/usr/local/lconf-standalone/app/modules/Api/lib/console/SshConsoleConnection.class.php',
  'ApiRestrictedCommandException' => '/usr/local/lconf-standalone/app/modules/Api/lib/console/BaseConsoleConnection.class.php',
  'ApiAuthorisationFailedException' => '/usr/local/lconf-standalone/app/modules/Api/lib/console/BaseConsoleConnection.class.php',
  'StoreFilterBase' => '/usr/local/lconf-standalone/app/modules/Api/lib/datastore/filter/StoreFilterBase.class.php',
  'GenericStoreFilterGroup' => '/usr/local/lconf-standalone/app/modules/Api/lib/datastore/filter/GenericStoreFilterGroup.class.php',
  'GenericStoreFilter' => '/usr/local/lconf-standalone/app/modules/Api/lib/datastore/filter/GenericStoreFilter.class.php',
  'StoreFilterField' => '/usr/local/lconf-standalone/app/modules/Api/lib/datastore/filter/StoreFilterField.class.php',
  'AbstractDataStoreModel' => '/usr/local/lconf-standalone/app/modules/Api/lib/datastore/AbstractDataStoreModel.class.php',
  'IcingaApiDataStoreModel' => '/usr/local/lconf-standalone/app/modules/Api/lib/datastore/IcingaApiDataStoreModel.class.php',
  'IcingaStoreFilterModifierModel' => '/usr/local/lconf-standalone/app/modules/Api/lib/datastore/filter/IcingaStoreFilterModifierModel.class.php',
  'IcingaStoreTargetModifierModel' => '/usr/local/lconf-standalone/app/modules/Api/lib/datastore/IcingaStoreTargetModifierModel.class.php',
  'IDataStoreModifier' => '/usr/local/lconf-standalone/app/modules/Api/lib/datastore/interfaces/IDataStoreModifier.php',
  'ApiStoreFilter' => '/usr/local/lconf-standalone/app/modules/Api/lib/datastore/filter/ApiStoreFilter.class.php',
  'ApiStoreFilterGroup' => '/usr/local/lconf-standalone/app/modules/Api/lib/datastore/filter/ApiStoreFilterGroup.class.php',
  'DataStoreFilterModifier' => '/usr/local/lconf-standalone/app/modules/Api/lib/datastore/DataStoreFilterModifier.class.php',
  'IcingaCommandsConfigHandler' => '/usr/local/lconf-standalone/app/modules/Api/lib/config/IcingaCommandsConfigHandler.class.php',
);

?>