<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2011-09-02T13:02:08+0000

return array (
  '/usr/local/lconf-standalone/app/config/autoload.xml' => 
  array (
    'class' => 'AgaviAutoloadConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/autoload.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/autoload.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/lib/agavi/src/config/defaults/autoload.xml' => 
  array (
    'class' => 'AgaviAutoloadConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/autoload.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/autoload.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/config/compile.xml' => 
  array (
    'class' => 'AgaviCompileConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/compile.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/compile.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/lib/agavi/src/config/defaults/compile.xml' => 
  array (
    'class' => 'AgaviCompileConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/compile.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/compile.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/config/settings.xml' => 
  array (
    'class' => 'AgaviSettingConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/settings.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/settings.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/config/factories.xml' => 
  array (
    'class' => 'AgaviFactoryConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/factories.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/factories.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/config/databases.xml' => 
  array (
    'class' => 'AppKitXIncludeConfigHandler',
    'parameters' => 
    array (
      'query' => '//ae:configurations/ae:configuration/databases:databases',
      'pointer' => 'xmlns(ae=http://agavi.org/agavi/config/global/envelope/1.0) xmlns(d=http://agavi.org/agavi/config/parts/databases/1.0) xpointer(//ae:configurations/ae:configuration/d:databases/d:database)',
      'includeNS' => 'databases',
      'debug' => true,
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/databases.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/databases.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/config/action_filters.xml' => 
  array (
    'class' => 'AgaviFilterConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/filters.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/filters.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/config/global_filters.xml' => 
  array (
    'class' => 'AgaviFilterConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/filters.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/filters.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/config/output_types.xml' => 
  array (
    'class' => 'AgaviOutputTypeConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/output_types.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/output_types.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/config/logging.xml' => 
  array (
    'class' => 'AgaviLoggingConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/logging.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/logging.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/config/rbac_definitions.xml' => 
  array (
    'class' => 'AgaviRbacDefinitionConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/rbac_definitions.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/rbac_definitions.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/config/routing.xml' => 
  array (
    'class' => 'AppKitXIncludeConfigHandler',
    'parameters' => 
    array (
      'query' => '//ae:configurations/ae:configuration[@context=\'__CONTEXT__\']/routing:routes/routing:route[@name=\'modules\']',
      'pointer' => 'xmlns(ae=http://agavi.org/agavi/config/global/envelope/1.0) xmlns(r=http://icinga.org/appkit/config/parts/routing/1.0) xpointer(//ae:configurations/ae:configuration[@context=\'__CONTEXT__\']/r:routes/node())',
      'includeNS' => 'routing',
      'handler' => 'AppKitRoutingConfigHandler',
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/app/modules/AppKit/lib/xml/xsl/routing.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/app/modules/AppKit/lib/xml/xsd/routing.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/lib/agavi/src/routing/soap/wsdl.xml' => 
  array (
    'class' => 'AgaviWsdlConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/routing.xsl',
      ),
      'compilation' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/routing/soap/wsdl.xsl',
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/config/translation.xml' => 
  array (
    'class' => 'AppKitXIncludeConfigHandler',
    'parameters' => 
    array (
      'query' => '//ae:configurations/ae:configuration/translation:translators[@default_domain=\'icinga.default\']',
      'pointer' => 'xmlns(ae=http://agavi.org/agavi/config/global/envelope/1.0) xmlns(t=http://agavi.org/agavi/config/parts/translation/1.0) xpointer(//ae:configurations/ae:configuration/t:translators/t:translator)',
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/translation.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/translation.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '%core.testing_dir%/config/suites.xml' => 
  array (
    'class' => 'AgaviTestSuitesConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/modules/*/config/autoload.xml' => 
  array (
    'class' => 'AgaviAutoloadConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/autoload.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/autoload.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/modules/*/config/action_filters.xml' => 
  array (
    'class' => 'AgaviFilterConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/filters.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/filters.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/modules/*/config/module.xml' => 
  array (
    'class' => 'AgaviModuleConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/module.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/module.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/modules/*/validate/*.xml' => 
  array (
    'class' => 'AgaviValidatorConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/validators.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/validators.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/modules/*/cache/*.xml' => 
  array (
    'class' => 'AgaviCachingConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsl/caching.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/lib/agavi/src/config/xsd/caching.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/lib/agavi/src/translation/data/locales/*.xml' => 
  array (
    'class' => 'AgaviLdmlConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/lib/agavi/src/translation/data/supplementalData.xml' => 
  array (
    'class' => 'AgaviLdmlSupplementalConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/config/javascript.xml' => 
  array (
    'class' => 'AppKitXIncludeConfigHandler',
    'parameters' => 
    array (
      'query' => '//ae:configurations/ae:configuration',
      'pointer' => 
      array (
        0 => 'xmlns(ae=http://agavi.org/agavi/config/global/envelope/1.0) xmlns(r=http://icinga.org/icinga/config/global/resource/1.0) xpointer(//ae:configurations/ae:configuration/r:javascript)',
        1 => 'xmlns(ae=http://agavi.org/agavi/config/global/envelope/1.0) xmlns(r=http://icinga.org/icinga/config/global/resource/1.0) xpointer(//ae:configurations/ae:configuration/r:jactions)',
      ),
      'handler' => 'AppKitResourceConfigHandler',
    ),
    'transformations' => 
    array (
      'single' => 
      array (
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/app/modules/AppKit/lib/xml/xsd/resource.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/config/css.xml' => 
  array (
    'class' => 'AppKitXIncludeConfigHandler',
    'parameters' => 
    array (
      'query' => '//ae:configurations/ae:configuration',
      'pointer' => 
      array (
        0 => 'xmlns(ae=http://agavi.org/agavi/config/global/envelope/1.0) xmlns(r=http://icinga.org/icinga/config/global/resource/1.0) xpointer(//ae:configurations/ae:configuration/r:css_import)',
        1 => 'xmlns(ae=http://agavi.org/agavi/config/global/envelope/1.0) xmlns(r=http://icinga.org/icinga/config/global/resource/1.0) xpointer(//ae:configurations/ae:configuration/r:css)',
      ),
      'handler' => 'AppKitResourceConfigHandler',
    ),
    'transformations' => 
    array (
      'single' => 
      array (
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/app/modules/AppKit/lib/xml/xsd/resource.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/config/menu.xml' => 
  array (
    'class' => 'AppKitXIncludeConfigHandler',
    'parameters' => 
    array (
      'query' => '//ae:configurations/ae:configuration',
      'pointer' => 'xmlns(ae=http://agavi.org/agavi/config/global/envelope/1.0) xmlns(m=http://icinga.org/icinga/config/global/menu/1.0) xpointer(//ae:configurations/ae:configuration/m:menu)',
      'handler' => 'AppKitMenuConfigHandler',
    ),
    'transformations' => 
    array (
      'single' => 
      array (
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/app/modules/AppKit/lib/xml/xsd/menu.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/config/schedules.xml' => 
  array (
    'class' => 'AppKitXIncludeConfigHandler',
    'parameters' => 
    array (
      'query' => '//settings:settings',
      'pointer' => 'xmlns(ae=http://agavi.org/agavi/config/global/envelope/1.0) xmlns(c=http://agavi.org/agavi/config/parts/settings/1.0) xpointer(//ae:configurations/ae:configuration/c:settings/node())',
      'handler' => 'AppKitSubSettingConfigHandler',
    ),
    'transformations' => 
    array (
      'single' => 
      array (
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
)

?>