<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/AppKit/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2011-09-02T13:02:09+0000

return array (
)

?>