<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/Api/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2011-09-02T13:02:09+0000

return array (
  '/usr/local/lconf-standalone/app/modules/*/config/icingaCommands.xml' => 
  array (
    'class' => 'IcingaCommandsConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/app/modules/Api/lib/xml/xsd/icingaCommands.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/modules/Api/config/access.xml' => 
  array (
    'class' => 'AccessConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/app/modules/Api/lib/xml/xsd/access.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/usr/local/lconf-standalone/app/modules/*/config/access.xml' => 
  array (
    'class' => 'AccessConfigModuleHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/usr/local/lconf-standalone/app/modules/Api/lib/xml/xsd/access-module.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
)

?>