<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/LConf/validate/Backend/connectionManager/connect.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2011-09-02T13:02:17+0000

${'_validator_connection_id'} = new AgaviNumberValidator();
${'_validator_connection_id'}->initialize($this->getContext(), array (
  'type' => 'int',
  'severity' => 'error',
  'required' => false,
  'class' => 'number',
  'name' => 'connection_id',
), array (
  0 => 'connection_id',
), array (
  '' => 'Validation of "connectionId" failed',
));
${'validationManager'}->addChild(${'_validator_connection_id'});
if($method == 'write') {
${'_validator_connection'} = new AgaviStringValidator();
${'_validator_connection'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => false,
  'class' => 'string',
  'name' => 'connection',
), array (
  0 => 'connection',
), array (
  '' => 'No connection provided',
));
${'validationManager'}->addChild(${'_validator_connection'});
${'_validator_testOnly'} = new AgaviIssetValidator();
${'_validator_testOnly'}->initialize($this->getContext(), array (
  'severity' => 'error',
  'required' => false,
  'class' => 'isset',
  'name' => 'testOnly',
), array (
  0 => 'testOnly',
), array (
  '' => 'Validation of testOnly failed',
));
${'validationManager'}->addChild(${'_validator_testOnly'});
}

?>