<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/LConf/validate/Backend/connectionManager/connectionListing.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2011-09-02T13:02:15+0000

${'_validator_scope'} = new AgaviInarrayValidator();
${'_validator_scope'}->initialize($this->getContext(), array (
  'sep' => ',',
  'severity' => 'error',
  'required' => false,
  'class' => 'inarray',
  'name' => 'scope',
), array (
  0 => 'scope',
), array (
  '' => 'Validation of parameter scope failed',
));
${'validationManager'}->addChild(${'_validator_scope'});
if($method == 'write') {
${'_validator_connections'} = new AgaviStringValidator();
${'_validator_connections'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => true,
  'class' => 'string',
  'name' => 'connections',
), array (
  0 => 'connections',
), array (
  '' => 'No connection to add provided',
));
${'validationManager'}->addChild(${'_validator_connections'});
}
if($method == 'remove') {
${'_validator_connection_id'} = new AgaviStringValidator();
${'_validator_connection_id'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => true,
  'class' => 'string',
  'name' => 'connection_id',
), array (
  0 => 'connection_id',
), array (
  '' => 'No connection to add provided',
));
${'validationManager'}->addChild(${'_validator_connection_id'});
}

?>