<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/config/css.xml
// Generated by: AppKitResourceConfigHandler
// Date: 2011-09-02T13:02:10+0000

$this->resources = array_merge_recursive($this->resources, array (
  'javascript' => 
  array (
  ),
  'css' => 
  array (
  ),
  'css_import' => 
  array (
    0 => '/js/ext3/resources/css/ext-all-notheme.css',
    1 => '/js/ext3/resources/css/xtheme-gray.css',
    2 => '/js/ext3/examples/ux/css/ux-all.css',
    3 => '/styles/icinga.css',
    4 => '/styles/icinga.site.css',
    5 => '/styles/icinga-icons.css',
    6 => '/styles/icinga-cronk-icons.css',
    7 => '/modules/LConf/resources/styles/main.css',
  ),
));
$this->jactions=array_merge_recursive($this->jactions, array (
));

?>