<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/config/databases.xml
// Generated by: AgaviDatabaseConfigHandler
// Date: 2011-09-02T13:02:09+0000

$database = new AppKitDoctrineDatabase();
$this->databases['icinga_web'] = $database;
$database->initialize($this, array (
  'dsn' => 'sqlite:////usr/local/lconf-standalone/app/data/users.db?mode=0666',
  'charset' => 'utf8',
  'manager_attributes' => 
  array (
    'Doctrine_Core::ATTR_MODEL_LOADING' => 'CONSERVATIVE',
  ),
  'load_models' => '/usr/local/lconf-standalone/app/modules/AppKit/lib/database/models/generated',
  'models_directory' => '/usr/local/lconf-standalone/app/modules/AppKit/lib/database/models',
  'date_format' => 'YYYY-MM-DD HH24:MI:SS',
  'caching' => 
  array (
    'enabled' => false,
    'driver' => 'apc',
    'use_query_cache' => true,
    'use_result_cache' => true,
    'result_cache_lifespan' => '60',
  ),
));
$this->defaultDatabaseName = 'icinga_web';

?>