<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/LConf/validate/Interface/DIT.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2011-09-02T13:02:10+0000

${'_validator_parentid'} = new AgaviStringValidator();
${'_validator_parentid'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => true,
  'class' => 'string',
  'name' => 'parentid',
), array (
  0 => 'parentid',
), array (
  '' => 'Validation of "parentId" failed!',
));
${'validationManager'}->addChild(${'_validator_parentid'});

?>