<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/lib/agavi/src/translation/data/locales/en.xml
// Generated by: AgaviLdmlConfigHandler
// Date: 2011-09-02T13:02:11+0000

return array (
  'layout' => 
  array (
    'orientation' => 
    array (
      'lines' => 'top-to-bottom',
      'characters' => 'left-to-right',
    ),
  ),
  'locale' => 
  array (
    'language' => 'en',
  ),
  'displayNames' => 
  array (
    'measurementSystemNames' => 
    array (
      'US' => 'US',
      'metric' => 'Metric',
    ),
    'languages' => 
    array (
      'aa' => 'Afar',
      'ab' => 'Abkhazian',
      'ace' => 'Achinese',
      'ach' => 'Acoli',
      'ada' => 'Adangme',
      'ady' => 'Adyghe',
      'ae' => 'Avestan',
      'af' => 'Afrikaans',
      'afa' => 'Afro-Asiatic (Other)',
      'afh' => 'Afrihili',
      'ain' => 'Ainu',
      'ak' => 'Akan',
      'akk' => 'Akkadian',
      'ale' => 'Aleut',
      'alg' => 'Algonquian Languages',
      'alt' => 'Southern Altai',
      'am' => 'Amharic',
      'an' => 'Aragonese',
      'ang' => 'Old English (ca.450-1100)',
      'anp' => 'Angika',
      'apa' => 'Apache Languages',
      'ar' => 'Arabic',
      'arc' => 'Aramaic',
      'arn' => 'Araucanian',
      'arp' => 'Arapaho',
      'art' => 'Artificial (Other)',
      'arw' => 'Arawak',
      'as' => 'Assamese',
      'ast' => 'Asturian',
      'ath' => 'Athapascan Languages',
      'aus' => 'Australian Languages',
      'av' => 'Avaric',
      'awa' => 'Awadhi',
      'ay' => 'Aymara',
      'az' => 'Azerbaijani',
      'ba' => 'Bashkir',
      'bad' => 'Banda',
      'bai' => 'Bamileke Languages',
      'bal' => 'Baluchi',
      'ban' => 'Balinese',
      'bas' => 'Basa',
      'bat' => 'Baltic (Other)',
      'be' => 'Belarusian',
      'bej' => 'Beja',
      'bem' => 'Bemba',
      'ber' => 'Berber',
      'bg' => 'Bulgarian',
      'bh' => 'Bihari',
      'bho' => 'Bhojpuri',
      'bi' => 'Bislama',
      'bik' => 'Bikol',
      'bin' => 'Bini',
      'bla' => 'Siksika',
      'bm' => 'Bambara',
      'bn' => 'Bengali',
      'bnt' => 'Bantu',
      'bo' => 'Tibetan',
      'br' => 'Breton',
      'bra' => 'Braj',
      'bs' => 'Bosnian',
      'btk' => 'Batak',
      'bua' => 'Buriat',
      'bug' => 'Buginese',
      'byn' => 'Blin',
      'ca' => 'Catalan',
      'cad' => 'Caddo',
      'cai' => 'Central American Indian (Other)',
      'car' => 'Carib',
      'cau' => 'Caucasian (Other)',
      'cch' => 'Atsam',
      'ce' => 'Chechen',
      'ceb' => 'Cebuano',
      'cel' => 'Celtic (Other)',
      'ch' => 'Chamorro',
      'chb' => 'Chibcha',
      'chg' => 'Chagatai',
      'chk' => 'Chuukese',
      'chm' => 'Mari',
      'chn' => 'Chinook Jargon',
      'cho' => 'Choctaw',
      'chp' => 'Chipewyan',
      'chr' => 'Cherokee',
      'chy' => 'Cheyenne',
      'cmc' => 'Chamic Languages',
      'co' => 'Corsican',
      'cop' => 'Coptic',
      'cpe' => 'Other English-based Creoles and Pidgins',
      'cpf' => 'Other French-based Creoles and Pidgins',
      'cpp' => 'Other Portuguese-based Creoles and Pidgins',
      'cr' => 'Cree',
      'crh' => 'Crimean Turkish; Crimean Tatar',
      'crp' => 'Creoles and Pidgins (Other)',
      'cs' => 'Czech',
      'csb' => 'Kashubian',
      'cu' => 'Church Slavic',
      'cus' => 'Cushitic (Other)',
      'cv' => 'Chuvash',
      'cy' => 'Welsh',
      'da' => 'Danish',
      'dak' => 'Dakota',
      'dar' => 'Dargwa',
      'day' => 'Dayak',
      'de' => 'German',
      'del' => 'Delaware',
      'den' => 'Slave',
      'dgr' => 'Dogrib',
      'din' => 'Dinka',
      'doi' => 'Dogri',
      'dra' => 'Dravidian (Other)',
      'dsb' => 'Lower Sorbian',
      'dua' => 'Duala',
      'dum' => 'Middle Dutch',
      'dv' => 'Divehi',
      'dyu' => 'Dyula',
      'dz' => 'Dzongkha',
      'ee' => 'Ewe',
      'efi' => 'Efik',
      'egy' => 'Egyptian (Ancient)',
      'eka' => 'Ekajuk',
      'el' => 'Greek',
      'elx' => 'Elamite',
      'en' => 'English',
      'enm' => 'Middle English',
      'eo' => 'Esperanto',
      'es' => 'Spanish',
      'et' => 'Estonian',
      'eu' => 'Basque',
      'ewo' => 'Ewondo',
      'fa' => 'Persian',
      'fan' => 'Fang',
      'fat' => 'Fanti',
      'ff' => 'Fulah',
      'fi' => 'Finnish',
      'fil' => 'Filipino',
      'fiu' => 'Finno - Ugrian (Other)',
      'fj' => 'Fijian',
      'fo' => 'Faroese',
      'fon' => 'Fon',
      'fr' => 'French',
      'frm' => 'Middle French',
      'fro' => 'Old French',
      'frr' => 'Northern Frisian',
      'frs' => 'Eastern Frisian',
      'fur' => 'Friulian',
      'fy' => 'Western Frisian',
      'ga' => 'Irish',
      'gaa' => 'Ga',
      'gay' => 'Gayo',
      'gba' => 'Gbaya',
      'gd' => 'Scottish Gaelic',
      'gem' => 'Germanic (Other)',
      'gez' => 'Geez',
      'gil' => 'Gilbertese',
      'gl' => 'Galician',
      'gmh' => 'Middle High German',
      'gn' => 'Guarani',
      'goh' => 'Old High German',
      'gon' => 'Gondi',
      'gor' => 'Gorontalo',
      'got' => 'Gothic',
      'grb' => 'Grebo',
      'grc' => 'Ancient Greek',
      'gsw' => 'Swiss German',
      'gu' => 'Gujarati',
      'gv' => 'Manx',
      'gwi' => 'Gwichʼin',
      'ha' => 'Hausa',
      'hai' => 'Haida',
      'haw' => 'Hawaiian',
      'he' => 'Hebrew',
      'hi' => 'Hindi',
      'hil' => 'Hiligaynon',
      'him' => 'Himachali',
      'hit' => 'Hittite',
      'hmn' => 'Hmong',
      'ho' => 'Hiri Motu',
      'hr' => 'Croatian',
      'hsb' => 'Upper Sorbian',
      'ht' => 'Haitian',
      'hu' => 'Hungarian',
      'hup' => 'Hupa',
      'hy' => 'Armenian',
      'hz' => 'Herero',
      'ia' => 'Interlingua',
      'iba' => 'Iban',
      'id' => 'Indonesian',
      'ie' => 'Interlingue',
      'ig' => 'Igbo',
      'ii' => 'Sichuan Yi',
      'ijo' => 'Ijo',
      'ik' => 'Inupiaq',
      'ilo' => 'Iloko',
      'inc' => 'Indic (Other)',
      'ine' => 'Indo-European (Other)',
      'inh' => 'Ingush',
      'io' => 'Ido',
      'ira' => 'Iranian (Other)',
      'iro' => 'Iroquoian languages',
      'is' => 'Icelandic',
      'it' => 'Italian',
      'iu' => 'Inuktitut',
      'ja' => 'Japanese',
      'jbo' => 'Lojban',
      'jpr' => 'Judeo-Persian',
      'jrb' => 'Judeo-Arabic',
      'jv' => 'Javanese',
      'ka' => 'Georgian',
      'kaa' => 'Kara-Kalpak',
      'kab' => 'Kabyle',
      'kac' => 'Kachin',
      'kaj' => 'Jju',
      'kam' => 'Kamba',
      'kar' => 'Karen',
      'kaw' => 'Kawi',
      'kbd' => 'Kabardian',
      'kcg' => 'Tyap',
      'kfo' => 'Koro',
      'kg' => 'Kongo',
      'kha' => 'Khasi',
      'khi' => 'Khoisan (Other)',
      'kho' => 'Khotanese',
      'ki' => 'Kikuyu',
      'kj' => 'Kuanyama',
      'kk' => 'Kazakh',
      'kl' => 'Kalaallisut',
      'km' => 'Khmer',
      'kmb' => 'Kimbundu',
      'kn' => 'Kannada',
      'ko' => 'Korean',
      'kok' => 'Konkani',
      'kos' => 'Kosraean',
      'kpe' => 'Kpelle',
      'kr' => 'Kanuri',
      'krc' => 'Karachay-Balkar',
      'krl' => 'Karelian',
      'kro' => 'Kru',
      'kru' => 'Kurukh',
      'ks' => 'Kashmiri',
      'ku' => 'Kurdish',
      'kum' => 'Kumyk',
      'kut' => 'Kutenai',
      'kv' => 'Komi',
      'kw' => 'Cornish',
      'ky' => 'Kirghiz',
      'la' => 'Latin',
      'lad' => 'Ladino',
      'lah' => 'Lahnda',
      'lam' => 'Lamba',
      'lb' => 'Luxembourgish',
      'lez' => 'Lezghian',
      'lg' => 'Ganda',
      'li' => 'Limburgish',
      'ln' => 'Lingala',
      'lo' => 'Lao',
      'lol' => 'Mongo',
      'loz' => 'Lozi',
      'lt' => 'Lithuanian',
      'lu' => 'Luba-Katanga',
      'lua' => 'Luba-Lulua',
      'lui' => 'Luiseno',
      'lun' => 'Lunda',
      'luo' => 'Luo',
      'lus' => 'Lushai',
      'lv' => 'Latvian',
      'mad' => 'Madurese',
      'mag' => 'Magahi',
      'mai' => 'Maithili',
      'mak' => 'Makasar',
      'man' => 'Mandingo',
      'map' => 'Austronesian',
      'mas' => 'Masai',
      'mdf' => 'Moksha',
      'mdr' => 'Mandar',
      'men' => 'Mende',
      'mg' => 'Malagasy',
      'mga' => 'Middle Irish',
      'mh' => 'Marshallese',
      'mi' => 'Maori',
      'mic' => 'Micmac',
      'min' => 'Minangkabau',
      'mis' => 'Miscellaneous Languages',
      'mk' => 'Macedonian',
      'mkh' => 'Mon-Khmer (Other)',
      'ml' => 'Malayalam',
      'mn' => 'Mongolian',
      'mnc' => 'Manchu',
      'mni' => 'Manipuri',
      'mno' => 'Manobo Languages',
      'mo' => 'Moldavian',
      'moh' => 'Mohawk',
      'mos' => 'Mossi',
      'mr' => 'Marathi',
      'ms' => 'Malay',
      'mt' => 'Maltese',
      'mul' => 'Multiple Languages',
      'mun' => 'Munda Languages',
      'mus' => 'Creek',
      'mwl' => 'Mirandese',
      'mwr' => 'Marwari',
      'my' => 'Burmese',
      'myn' => 'Mayan languages',
      'myv' => 'Erzya',
      'na' => 'Nauru',
      'nah' => 'Nahuatl',
      'nai' => 'North American Indian (Other)',
      'nap' => 'Neapolitan',
      'nb' => 'Norwegian Bokmål',
      'nd' => 'North Ndebele',
      'nds' => 'Low German; Low Saxon',
      'ne' => 'Nepali',
      'new' => 'Newari',
      'ng' => 'Ndonga',
      'nia' => 'Nias',
      'nic' => 'Niger - Kordofanian (Other)',
      'niu' => 'Niuean',
      'nl' => 'Dutch',
      'nn' => 'Norwegian Nynorsk',
      'no' => 'Norwegian',
      'nog' => 'Nogai',
      'non' => 'Norse, Old',
      'nqo' => 'N’Ko',
      'nr' => 'South Ndebele',
      'nso' => 'Northern Sotho',
      'nub' => 'Nubian Languages',
      'nv' => 'Navajo',
      'nwc' => 'Classical Newari',
      'ny' => 'Nyanja; Chichewa; Chewa',
      'nym' => 'Nyamwezi',
      'nyn' => 'Nyankole',
      'nyo' => 'Nyoro',
      'nzi' => 'Nzima',
      'oc' => 'Occitan (post 1500); Provençal',
      'oj' => 'Ojibwa',
      'om' => 'Oromo',
      'or' => 'Oriya',
      'os' => 'Ossetic',
      'osa' => 'Osage',
      'ota' => 'Ottoman Turkish',
      'oto' => 'Otomian Languages',
      'pa' => 'Punjabi',
      'paa' => 'Papuan (Other)',
      'pag' => 'Pangasinan',
      'pal' => 'Pahlavi',
      'pam' => 'Pampanga',
      'pap' => 'Papiamento',
      'pau' => 'Palauan',
      'peo' => 'Old Persian',
      'phi' => 'Philippine (Other)',
      'phn' => 'Phoenician',
      'pi' => 'Pali',
      'pl' => 'Polish',
      'pon' => 'Pohnpeian',
      'pra' => 'Prakrit Languages',
      'pro' => 'Old Provençal',
      'ps' => 'Pashto',
      'pt' => 'Portuguese',
      'qu' => 'Quechua',
      'raj' => 'Rajasthani',
      'rap' => 'Rapanui',
      'rar' => 'Rarotongan',
      'rm' => 'Rhaeto-Romance',
      'rn' => 'Rundi',
      'ro' => 'Romanian',
      'roa' => 'Romance (Other)',
      'rom' => 'Romany',
      'root' => 'Root',
      'ru' => 'Russian',
      'rup' => 'Aromanian',
      'rw' => 'Kinyarwanda',
      'sa' => 'Sanskrit',
      'sad' => 'Sandawe',
      'sah' => 'Yakut',
      'sai' => 'South American Indian (Other)',
      'sal' => 'Salishan languages',
      'sam' => 'Samaritan Aramaic',
      'sas' => 'Sasak',
      'sat' => 'Santali',
      'sc' => 'Sardinian',
      'scn' => 'Sicilian',
      'sco' => 'Scots',
      'sd' => 'Sindhi',
      'se' => 'Northern Sami',
      'sel' => 'Selkup',
      'sem' => 'Semitic (Other)',
      'sg' => 'Sango',
      'sga' => 'Old Irish',
      'sgn' => 'Sign Languages',
      'sh' => 'Serbo-Croatian',
      'shn' => 'Shan',
      'si' => 'Sinhalese',
      'sid' => 'Sidamo',
      'sio' => 'Siouan Languages',
      'sit' => 'Sino-Tibetan (Other)',
      'sk' => 'Slovak',
      'sl' => 'Slovenian',
      'sla' => 'Slavic (Other)',
      'sm' => 'Samoan',
      'sma' => 'Southern Sami',
      'smi' => 'Sami languages (Other)',
      'smj' => 'Lule Sami',
      'smn' => 'Inari Sami',
      'sms' => 'Skolt Sami',
      'sn' => 'Shona',
      'snk' => 'Soninke',
      'so' => 'Somali',
      'sog' => 'Sogdien',
      'son' => 'Songhai',
      'sq' => 'Albanian',
      'sr' => 'Serbian',
      'srn' => 'Sranan Tongo',
      'srr' => 'Serer',
      'ss' => 'Swati',
      'ssa' => 'Nilo-Saharan (Other)',
      'st' => 'Southern Sotho',
      'su' => 'Sundanese',
      'suk' => 'Sukuma',
      'sus' => 'Susu',
      'sux' => 'Sumerian',
      'sv' => 'Swedish',
      'sw' => 'Swahili',
      'syr' => 'Syriac',
      'ta' => 'Tamil',
      'tai' => 'Tai (Other)',
      'te' => 'Telugu',
      'tem' => 'Timne',
      'ter' => 'Tereno',
      'tet' => 'Tetum',
      'tg' => 'Tajik',
      'th' => 'Thai',
      'ti' => 'Tigrinya',
      'tig' => 'Tigre',
      'tiv' => 'Tiv',
      'tk' => 'Turkmen',
      'tkl' => 'Tokelau',
      'tl' => 'Tagalog',
      'tlh' => 'Klingon',
      'tli' => 'Tlingit',
      'tmh' => 'Tamashek',
      'tn' => 'Tswana',
      'to' => 'Tonga (Tonga Islands)',
      'tog' => 'Tonga (Nyasa)',
      'tpi' => 'Tok Pisin',
      'tr' => 'Turkish',
      'ts' => 'Tsonga',
      'tsi' => 'Tsimshian',
      'tt' => 'Tatar',
      'tum' => 'Tumbuka',
      'tup' => 'Tupi languages',
      'tut' => 'Altaic (Other)',
      'tvl' => 'Tuvalu',
      'tw' => 'Twi',
      'ty' => 'Tahitian',
      'tyv' => 'Tuvinian',
      'udm' => 'Udmurt',
      'ug' => 'Uighur',
      'uga' => 'Ugaritic',
      'uk' => 'Ukrainian',
      'umb' => 'Umbundu',
      'und' => 'Unknown or Invalid Language',
      'ur' => 'Urdu',
      'uz' => 'Uzbek',
      'vai' => 'Vai',
      've' => 'Venda',
      'vi' => 'Vietnamese',
      'vo' => 'Volapük',
      'vot' => 'Votic',
      'wa' => 'Walloon',
      'wak' => 'Wakashan Languages',
      'wal' => 'Walamo',
      'war' => 'Waray',
      'was' => 'Washo',
      'wen' => 'Sorbian Languages',
      'wo' => 'Wolof',
      'xal' => 'Kalmyk',
      'xh' => 'Xhosa',
      'yao' => 'Yao',
      'yap' => 'Yapese',
      'yi' => 'Yiddish',
      'yo' => 'Yoruba',
      'ypk' => 'Yupik Languages',
      'za' => 'Zhuang',
      'zap' => 'Zapotec',
      'zen' => 'Zenaga',
      'zh' => 'Chinese',
      'znd' => 'Zande',
      'zu' => 'Zulu',
      'zun' => 'Zuni',
      'zza' => 'Zaza',
      'zxx' => 'No linguistic content',
    ),
    'scripts' => 
    array (
      'Arab' => 'Arabic',
      'Armn' => 'Armenian',
      'Bali' => 'Balinese',
      'Batk' => 'Batak',
      'Beng' => 'Bengali',
      'Blis' => 'Blissymbols',
      'Bopo' => 'Bopomofo',
      'Brah' => 'Brahmi',
      'Brai' => 'Braille',
      'Bugi' => 'Buginese',
      'Buhd' => 'Buhid',
      'Cans' => 'Unified Canadian Aboriginal Symbols',
      'Cari' => 'Carian',
      'Cham' => 'Cham',
      'Cher' => 'Cherokee',
      'Cirt' => 'Cirth',
      'Copt' => 'Coptic',
      'Cprt' => 'Cypriot',
      'Cyrl' => 'Cyrillic',
      'Cyrs' => 'Cyrillic (Old Church Slavonic variant)',
      'Deva' => 'Devanagari',
      'Dsrt' => 'Deseret',
      'Egyd' => 'Egyptian demotic',
      'Egyh' => 'Egyptian hieratic',
      'Egyp' => 'Egyptian hieroglyphs',
      'Ethi' => 'Ethiopic',
      'Geok' => 'Khutsuri (Asomtavruli and Nuskhuri)',
      'Geor' => 'Georgian',
      'Glag' => 'Glagolitic',
      'Goth' => 'Gothic',
      'Grek' => 'Greek',
      'Gujr' => 'Gujarati',
      'Guru' => 'Gurmukhi',
      'Hang' => 'Hangul',
      'Hani' => 'Han',
      'Hano' => 'Hanunoo',
      'Hans' => 'Simplified Han',
      'Hant' => 'Traditional Han',
      'Hebr' => 'Hebrew',
      'Hira' => 'Hiragana',
      'Hmng' => 'Pahawh Hmong',
      'Hrkt' => 'Katakana or Hiragana',
      'Hung' => 'Old Hungarian',
      'Inds' => 'Indus (Harappan)',
      'Ital' => 'Old Italic',
      'Jpan' => 'Japanese',
      'Java' => 'Javanese',
      'Kali' => 'Kayah Li',
      'Kana' => 'Katakana',
      'Khar' => 'Kharoshthi',
      'Khmr' => 'Khmer',
      'Knda' => 'Kannada',
      'Lana' => 'Lanna',
      'Laoo' => 'Lao',
      'Latf' => 'Latin (Fraktur variant)',
      'Latg' => 'Latin (Gaelic variant)',
      'Latn' => 'Latin',
      'Lepc' => 'Lepcha (Róng)',
      'Limb' => 'Limbu',
      'Lina' => 'Linear A',
      'Linb' => 'Linear B',
      'Lyci' => 'Lycian',
      'Lydi' => 'Lydian',
      'Mand' => 'Mandaean',
      'Maya' => 'Mayan hieroglyphs',
      'Mero' => 'Meroitic',
      'Mlym' => 'Malayalam',
      'Mong' => 'Mongolian',
      'Mymr' => 'Myanmar',
      'Nkoo' => 'N’Ko',
      'Ogam' => 'Ogham',
      'Olck' => 'Ol Chiki',
      'Orkh' => 'Orkhon',
      'Orya' => 'Oriya',
      'Osma' => 'Osmanya',
      'Perm' => 'Old Permic',
      'Phag' => 'Phags-pa',
      'Phnx' => 'Phoenician',
      'Plrd' => 'Pollard Phonetic',
      'Qaai' => 'Inherited',
      'Rjng' => 'Rejang',
      'Roro' => 'Rongorongo',
      'Runr' => 'Runic',
      'Sara' => 'Sarati',
      'Saur' => 'Saurashtra',
      'Sgnw' => 'SignWriting',
      'Shaw' => 'Shavian',
      'Sinh' => 'Sinhala',
      'Sund' => 'Sundanese',
      'Sylo' => 'Syloti Nagri',
      'Syrc' => 'Syriac',
      'Syre' => 'Syriac (Estrangelo variant)',
      'Syrj' => 'Syriac (Western variant)',
      'Syrn' => 'Syriac (Eastern variant)',
      'Tagb' => 'Tagbanwa',
      'Tale' => 'Tai Le',
      'Talu' => 'New Tai Lue',
      'Taml' => 'Tamil',
      'Telu' => 'Telugu',
      'Teng' => 'Tengwar',
      'Tfng' => 'Tifinagh (Berber)',
      'Tglg' => 'Tagalog',
      'Thaa' => 'Thaana',
      'Thai' => 'Thai',
      'Tibt' => 'Tibetan',
      'Ugar' => 'Ugaritic',
      'Vaii' => 'Vai',
      'Visp' => 'Visible Speech',
      'Xpeo' => 'Old Persian',
      'Xsux' => 'Sumero-Akkadian Cuneiform',
      'Yiii' => 'Yi',
      'Zxxx' => 'Unwritten',
      'Zyyy' => 'Common',
      'Zzzz' => 'Unknown or Invalid Script',
    ),
    'territories' => 
    array (
      '001' => 'World',
      '002' => 'Africa',
      '003' => 'North America',
      '005' => 'South America',
      '009' => 'Oceania',
      '011' => 'Western Africa',
      '013' => 'Central America',
      '014' => 'Eastern Africa',
      '015' => 'Northern Africa',
      '017' => 'Middle Africa',
      '018' => 'Southern Africa',
      '019' => 'Americas',
      '021' => 'Northern America',
      '029' => 'Caribbean',
      '030' => 'Eastern Asia',
      '034' => 'Southern Asia',
      '035' => 'South-Eastern Asia',
      '039' => 'Southern Europe',
      '053' => 'Australia and New Zealand',
      '054' => 'Melanesia',
      '057' => 'Micronesian Region',
      '061' => 'Polynesia',
      '062' => 'South-Central Asia',
      142 => 'Asia',
      143 => 'Central Asia',
      145 => 'Western Asia',
      150 => 'Europe',
      151 => 'Eastern Europe',
      154 => 'Northern Europe',
      155 => 'Western Europe',
      172 => 'Commonwealth of Independent States',
      200 => 'Czechoslovakia',
      419 => 'Latin America and the Caribbean',
      830 => 'Channel Islands',
      'AD' => 'Andorra',
      'AE' => 'United Arab Emirates',
      'AF' => 'Afghanistan',
      'AG' => 'Antigua and Barbuda',
      'AI' => 'Anguilla',
      'AL' => 'Albania',
      'AM' => 'Armenia',
      'AN' => 'Netherlands Antilles',
      'AO' => 'Angola',
      'AQ' => 'Antarctica',
      'AR' => 'Argentina',
      'AS' => 'American Samoa',
      'AT' => 'Austria',
      'AU' => 'Australia',
      'AW' => 'Aruba',
      'AX' => 'Aland Islands',
      'AZ' => 'Azerbaijan',
      'BA' => 'Bosnia and Herzegovina',
      'BB' => 'Barbados',
      'BD' => 'Bangladesh',
      'BE' => 'Belgium',
      'BF' => 'Burkina Faso',
      'BG' => 'Bulgaria',
      'BH' => 'Bahrain',
      'BI' => 'Burundi',
      'BJ' => 'Benin',
      'BM' => 'Bermuda',
      'BN' => 'Brunei',
      'BO' => 'Bolivia',
      'BQ' => 'British Antarctic Territory',
      'BR' => 'Brazil',
      'BS' => 'Bahamas',
      'BT' => 'Bhutan',
      'BV' => 'Bouvet Island',
      'BW' => 'Botswana',
      'BY' => 'Belarus',
      'BZ' => 'Belize',
      'CA' => 'Canada',
      'CC' => 'Cocos (Keeling) Islands',
      'CD' => 'Congo (Kinshasa)',
      'CF' => 'Central African Republic',
      'CG' => 'Congo (Brazzaville)',
      'CH' => 'Switzerland',
      'CI' => 'Ivory Coast',
      'CK' => 'Cook Islands',
      'CL' => 'Chile',
      'CM' => 'Cameroon',
      'CN' => 'China',
      'CO' => 'Colombia',
      'CR' => 'Costa Rica',
      'CS' => 'Serbia And Montenegro',
      'CT' => 'Canton and Enderbury Islands',
      'CU' => 'Cuba',
      'CV' => 'Cape Verde',
      'CX' => 'Christmas Island',
      'CY' => 'Cyprus',
      'CZ' => 'Czech Republic',
      'DD' => 'East Germany',
      'DE' => 'Germany',
      'DJ' => 'Djibouti',
      'DK' => 'Denmark',
      'DM' => 'Dominica',
      'DO' => 'Dominican Republic',
      'DZ' => 'Algeria',
      'EC' => 'Ecuador',
      'EE' => 'Estonia',
      'EG' => 'Egypt',
      'EH' => 'Western Sahara',
      'ER' => 'Eritrea',
      'ES' => 'Spain',
      'ET' => 'Ethiopia',
      'FI' => 'Finland',
      'FJ' => 'Fiji',
      'FK' => 'Falkland Islands',
      'FM' => 'Micronesia',
      'FO' => 'Faroe Islands',
      'FQ' => 'French Southern and Antarctic Territories',
      'FR' => 'France',
      'FX' => 'Metropolitan France',
      'GA' => 'Gabon',
      'GB' => 'United Kingdom',
      'GD' => 'Grenada',
      'GE' => 'Georgia',
      'GF' => 'French Guiana',
      'GG' => 'Guernsey',
      'GH' => 'Ghana',
      'GI' => 'Gibraltar',
      'GL' => 'Greenland',
      'GM' => 'Gambia',
      'GN' => 'Guinea',
      'GP' => 'Guadeloupe',
      'GQ' => 'Equatorial Guinea',
      'GR' => 'Greece',
      'GS' => 'South Georgia and the South Sandwich Islands',
      'GT' => 'Guatemala',
      'GU' => 'Guam',
      'GW' => 'Guinea-Bissau',
      'GY' => 'Guyana',
      'HK' => 'Hong Kong SAR China',
      'HM' => 'Heard Island and McDonald Islands',
      'HN' => 'Honduras',
      'HR' => 'Croatia',
      'HT' => 'Haiti',
      'HU' => 'Hungary',
      'ID' => 'Indonesia',
      'IE' => 'Ireland',
      'IL' => 'Israel',
      'IM' => 'Isle of Man',
      'IN' => 'India',
      'IO' => 'British Indian Ocean Territory',
      'IQ' => 'Iraq',
      'IR' => 'Iran',
      'IS' => 'Iceland',
      'IT' => 'Italy',
      'JE' => 'Jersey',
      'JM' => 'Jamaica',
      'JO' => 'Jordan',
      'JP' => 'Japan',
      'JT' => 'Johnston Island',
      'KE' => 'Kenya',
      'KG' => 'Kyrgyzstan',
      'KH' => 'Cambodia',
      'KI' => 'Kiribati',
      'KM' => 'Comoros',
      'KN' => 'Saint Kitts and Nevis',
      'KP' => 'North Korea',
      'KR' => 'South Korea',
      'KW' => 'Kuwait',
      'KY' => 'Cayman Islands',
      'KZ' => 'Kazakhstan',
      'LA' => 'Laos',
      'LB' => 'Lebanon',
      'LC' => 'Saint Lucia',
      'LI' => 'Liechtenstein',
      'LK' => 'Sri Lanka',
      'LR' => 'Liberia',
      'LS' => 'Lesotho',
      'LT' => 'Lithuania',
      'LU' => 'Luxembourg',
      'LV' => 'Latvia',
      'LY' => 'Libya',
      'MA' => 'Morocco',
      'MC' => 'Monaco',
      'MD' => 'Moldova',
      'ME' => 'Montenegro',
      'MG' => 'Madagascar',
      'MH' => 'Marshall Islands',
      'MI' => 'Midway Islands',
      'MK' => 'Macedonia',
      'ML' => 'Mali',
      'MM' => 'Myanmar',
      'MN' => 'Mongolia',
      'MO' => 'Macao SAR China',
      'MP' => 'Northern Mariana Islands',
      'MQ' => 'Martinique',
      'MR' => 'Mauritania',
      'MS' => 'Montserrat',
      'MT' => 'Malta',
      'MU' => 'Mauritius',
      'MV' => 'Maldives',
      'MW' => 'Malawi',
      'MX' => 'Mexico',
      'MY' => 'Malaysia',
      'MZ' => 'Mozambique',
      'NA' => 'Namibia',
      'NC' => 'New Caledonia',
      'NE' => 'Niger',
      'NF' => 'Norfolk Island',
      'NG' => 'Nigeria',
      'NI' => 'Nicaragua',
      'NL' => 'Netherlands',
      'NO' => 'Norway',
      'NP' => 'Nepal',
      'NQ' => 'Dronning Maud Land',
      'NR' => 'Nauru',
      'NT' => 'Neutral Zone',
      'NU' => 'Niue',
      'NZ' => 'New Zealand',
      'OM' => 'Oman',
      'PA' => 'Panama',
      'PC' => 'Pacific Islands Trust Territory',
      'PE' => 'Peru',
      'PF' => 'French Polynesia',
      'PG' => 'Papua New Guinea',
      'PH' => 'Philippines',
      'PK' => 'Pakistan',
      'PL' => 'Poland',
      'PM' => 'Saint Pierre and Miquelon',
      'PN' => 'Pitcairn',
      'PR' => 'Puerto Rico',
      'PS' => 'Palestinian Territory',
      'PT' => 'Portugal',
      'PU' => 'U.S. Miscellaneous Pacific Islands',
      'PW' => 'Palau',
      'PY' => 'Paraguay',
      'PZ' => 'Panama Canal Zone',
      'QA' => 'Qatar',
      'QO' => 'Outlying Oceania',
      'QU' => 'European Union',
      'RE' => 'Reunion',
      'RO' => 'Romania',
      'RS' => 'Serbia',
      'RU' => 'Russia',
      'RW' => 'Rwanda',
      'SA' => 'Saudi Arabia',
      'SB' => 'Solomon Islands',
      'SC' => 'Seychelles',
      'SD' => 'Sudan',
      'SE' => 'Sweden',
      'SG' => 'Singapore',
      'SH' => 'Saint Helena',
      'SI' => 'Slovenia',
      'SJ' => 'Svalbard and Jan Mayen',
      'SK' => 'Slovakia',
      'SL' => 'Sierra Leone',
      'SM' => 'San Marino',
      'SN' => 'Senegal',
      'SO' => 'Somalia',
      'SR' => 'Suriname',
      'ST' => 'Sao Tome and Principe',
      'SU' => 'Union of Soviet Socialist Republics',
      'SV' => 'El Salvador',
      'SY' => 'Syria',
      'SZ' => 'Swaziland',
      'TC' => 'Turks and Caicos Islands',
      'TD' => 'Chad',
      'TF' => 'French Southern Territories',
      'TG' => 'Togo',
      'TH' => 'Thailand',
      'TJ' => 'Tajikistan',
      'TK' => 'Tokelau',
      'TL' => 'East Timor',
      'TM' => 'Turkmenistan',
      'TN' => 'Tunisia',
      'TO' => 'Tonga',
      'TR' => 'Turkey',
      'TT' => 'Trinidad and Tobago',
      'TV' => 'Tuvalu',
      'TW' => 'Taiwan',
      'TZ' => 'Tanzania',
      'UA' => 'Ukraine',
      'UG' => 'Uganda',
      'UM' => 'United States Minor Outlying Islands',
      'US' => 'United States',
      'UY' => 'Uruguay',
      'UZ' => 'Uzbekistan',
      'VA' => 'Vatican',
      'VC' => 'Saint Vincent and the Grenadines',
      'VD' => 'North Vietnam',
      'VE' => 'Venezuela',
      'VG' => 'British Virgin Islands',
      'VI' => 'U.S. Virgin Islands',
      'VN' => 'Vietnam',
      'VU' => 'Vanuatu',
      'WF' => 'Wallis and Futuna',
      'WK' => 'Wake Island',
      'WS' => 'Samoa',
      'YD' => 'People\'s Democratic Republic of Yemen',
      'YE' => 'Yemen',
      'YT' => 'Mayotte',
      'ZA' => 'South Africa',
      'ZM' => 'Zambia',
      'ZW' => 'Zimbabwe',
      'ZZ' => 'Unknown or Invalid Region',
    ),
    'variants' => 
    array (
      1901 => 'Traditional German orthography',
      1996 => 'German orthography of 1996',
      'BOONT' => 'Boontling',
      'AREVELA' => 'Eastern Armenian',
      'AREVMDA' => 'Western Armenian',
      'GAULISH' => 'Gaulish',
      'GUOYU' => 'Mandarin or Standard Chinese',
      'HAKKA' => 'Hakka',
      'LOJBAN' => 'Lojban',
      'NEDIS' => 'Natisone dialect',
      'POLYTONI' => 'Polytonic',
      'POSIX' => 'Computer',
      'REVISED' => 'Revised Orthography',
      'ROZAJ' => 'Resian',
      'SAAHO' => 'Saho',
      'SCOUSE' => 'Scouse',
      'XIANG' => 'Xiang or Hunanese',
    ),
    'keys' => 
    array (
      'calendar' => 'Calendar',
      'collation' => 'Collation',
      'currency' => 'Currency',
    ),
  ),
  'delimiters' => 
  array (
    'quotationStart' => '“',
    'quotationEnd' => '”',
    'alternateQuotationStart' => '‘',
    'alternateQuotationEnd' => '’',
  ),
  'calendars' => 
  array (
    'default' => 'gregorian',
    'buddhist' => 
    array (
      'eras' => 
      array (
        'abbreviated' => 
        array (
          0 => 'BE',
        ),
      ),
      'dateFormats' => 
      array (
        'default' => 'medium',
        'full' => 
        array (
          'pattern' => 'EEEE, MMMM d, yyyy G',
        ),
        'long' => 
        array (
          'pattern' => 'MMMM d, yyyy G',
        ),
        'medium' => 
        array (
          'pattern' => 'MMM d, yyyy G',
        ),
        'short' => 
        array (
          'pattern' => 'M/d/yyyy',
        ),
      ),
      'timeFormats' => 
      array (
        'default' => 'medium',
        'full' => 
        array (
          'pattern' => 'HH:mm:ss z',
        ),
        'long' => 
        array (
          'pattern' => 'HH:mm:ss z',
        ),
        'medium' => 
        array (
          'pattern' => 'HH:mm:ss',
        ),
        'short' => 
        array (
          'pattern' => 'HH:mm',
        ),
      ),
      'dateTimeFormats' => 
      array (
        'default' => '__default',
        'formats' => 
        array (
          '__default' => '{1} {0}',
        ),
        'availableFormats' => 
        array (
          'yyQ' => 'Q yy',
        ),
        'appendItems' => 
        array (
          'Day' => '{0} ({2}: {1})',
          'Day-Of-Week' => '{0} {1}',
          'Era' => '{0} {1}',
          'Hour' => '{0} ({2}: {1})',
          'Minute' => '{0} ({2}: {1})',
          'Month' => '{0} ({2}: {1})',
          'Quarter' => '{0} ({2}: {1})',
          'Second' => '{0} ({2}: {1})',
          'Timezone' => '{0} {1}',
          'Week' => '{0} ({2}: {1})',
          'Year' => '{0} {1}',
        ),
      ),
    ),
    'chinese' => 
    array (
      'dateFormats' => 
      array (
        'default' => 'medium',
        'full' => 
        array (
          'pattern' => 'EEEE y\'x\'G-Ml-d',
        ),
        'long' => 
        array (
          'pattern' => 'y\'x\'G-Ml-d',
        ),
        'medium' => 
        array (
          'pattern' => 'y\'x\'G-Ml-d',
        ),
        'short' => 
        array (
          'pattern' => 'y\'x\'G-Ml-d',
        ),
      ),
      'timeFormats' => 
      array (
        'default' => 'medium',
        'full' => 
        array (
          'pattern' => 'HH:mm:ss z',
        ),
        'long' => 
        array (
          'pattern' => 'HH:mm:ss z',
        ),
        'medium' => 
        array (
          'pattern' => 'HH:mm:ss',
        ),
        'short' => 
        array (
          'pattern' => 'HH:mm',
        ),
      ),
      'dateTimeFormats' => 
      array (
        'default' => '__default',
        'formats' => 
        array (
          '__default' => '{1} {0}',
        ),
        'availableFormats' => 
        array (
          'yyQ' => 'Q yy',
        ),
        'appendItems' => 
        array (
          'Day' => '{0} ({2}: {1})',
          'Day-Of-Week' => '{0} {1}',
          'Era' => '{0} {1}',
          'Hour' => '{0} ({2}: {1})',
          'Minute' => '{0} ({2}: {1})',
          'Month' => '{0} ({2}: {1})',
          'Quarter' => '{0} ({2}: {1})',
          'Second' => '{0} ({2}: {1})',
          'Timezone' => '{0} {1}',
          'Week' => '{0} ({2}: {1})',
          'Year' => '{0} {1}',
        ),
      ),
    ),
    'coptic' => 
    array (
      'months' => 
      array (
        'default' => 'format',
        'format' => 
        array (
          'default' => 'wide',
          'abbreviated' => 
          array (
            1 => 'Tout',
            2 => 'Baba',
            3 => 'Hator',
            4 => 'Kiahk',
            5 => 'Toba',
            6 => 'Amshir',
            7 => 'Baramhat',
            8 => 'Baramouda',
            9 => 'Bashans',
            10 => 'Paona',
            11 => 'Epep',
            12 => 'Mesra',
            13 => 'Nasie',
          ),
          'wide' => 
          array (
            1 => 'Tout',
            2 => 'Baba',
            3 => 'Hator',
            4 => 'Kiahk',
            5 => 'Toba',
            6 => 'Amshir',
            7 => 'Baramhat',
            8 => 'Baramouda',
            9 => 'Bashans',
            10 => 'Paona',
            11 => 'Epep',
            12 => 'Mesra',
            13 => 'Nasie',
          ),
        ),
      ),
      'eras' => 
      array (
        'abbreviated' => 
        array (
          0 => 'ERA0',
          1 => 'ERA1',
        ),
      ),
      'dateFormats' => 
      array (
        'default' => 'medium',
        'full' => 
        array (
          'pattern' => 'EEEE, yyyy MMMM dd',
        ),
        'long' => 
        array (
          'pattern' => 'yyyy MMMM d',
        ),
        'medium' => 
        array (
          'pattern' => 'yyyy MMM d',
        ),
        'short' => 
        array (
          'pattern' => 'yy/MM/dd',
        ),
      ),
      'timeFormats' => 
      array (
        'default' => 'medium',
        'full' => 
        array (
          'pattern' => 'HH:mm:ss z',
        ),
        'long' => 
        array (
          'pattern' => 'HH:mm:ss z',
        ),
        'medium' => 
        array (
          'pattern' => 'HH:mm:ss',
        ),
        'short' => 
        array (
          'pattern' => 'HH:mm',
        ),
      ),
      'dateTimeFormats' => 
      array (
        'default' => '__default',
        'formats' => 
        array (
          '__default' => '{1} {0}',
        ),
        'availableFormats' => 
        array (
          'yyQ' => 'Q yy',
        ),
        'appendItems' => 
        array (
          'Day' => '{0} ({2}: {1})',
          'Day-Of-Week' => '{0} {1}',
          'Era' => '{0} {1}',
          'Hour' => '{0} ({2}: {1})',
          'Minute' => '{0} ({2}: {1})',
          'Month' => '{0} ({2}: {1})',
          'Quarter' => '{0} ({2}: {1})',
          'Second' => '{0} ({2}: {1})',
          'Timezone' => '{0} {1}',
          'Week' => '{0} ({2}: {1})',
          'Year' => '{0} {1}',
        ),
      ),
    ),
    'ethiopic' => 
    array (
      'months' => 
      array (
        'default' => 'format',
        'format' => 
        array (
          'default' => 'wide',
          'abbreviated' => 
          array (
            1 => 'Meskerem',
            2 => 'Tekemt',
            3 => 'Hedar',
            4 => 'Tahsas',
            5 => 'Ter',
            6 => 'Yekatit',
            7 => 'Megabit',
            8 => 'Miazia',
            9 => 'Genbot',
            10 => 'Sene',
            11 => 'Hamle',
            12 => 'Nehasse',
            13 => 'Pagumen',
          ),
          'wide' => 
          array (
            1 => 'Meskerem',
            2 => 'Tekemt',
            3 => 'Hedar',
            4 => 'Tahsas',
            5 => 'Ter',
            6 => 'Yekatit',
            7 => 'Megabit',
            8 => 'Miazia',
            9 => 'Genbot',
            10 => 'Sene',
            11 => 'Hamle',
            12 => 'Nehasse',
            13 => 'Pagumen',
          ),
        ),
      ),
      'eras' => 
      array (
        'abbreviated' => 
        array (
          0 => 'ERA0',
          1 => 'ERA1',
        ),
      ),
      'dateFormats' => 
      array (
        'default' => 'medium',
        'full' => 
        array (
          'pattern' => 'EEEE, yyyy MMMM dd',
        ),
        'long' => 
        array (
          'pattern' => 'yyyy MMMM d',
        ),
        'medium' => 
        array (
          'pattern' => 'yyyy MMM d',
        ),
        'short' => 
        array (
          'pattern' => 'yy/MM/dd',
        ),
      ),
      'timeFormats' => 
      array (
        'default' => 'medium',
        'full' => 
        array (
          'pattern' => 'HH:mm:ss z',
        ),
        'long' => 
        array (
          'pattern' => 'HH:mm:ss z',
        ),
        'medium' => 
        array (
          'pattern' => 'HH:mm:ss',
        ),
        'short' => 
        array (
          'pattern' => 'HH:mm',
        ),
      ),
      'dateTimeFormats' => 
      array (
        'default' => '__default',
        'formats' => 
        array (
          '__default' => '{1} {0}',
        ),
        'availableFormats' => 
        array (
          'yyQ' => 'Q yy',
        ),
        'appendItems' => 
        array (
          'Day' => '{0} ({2}: {1})',
          'Day-Of-Week' => '{0} {1}',
          'Era' => '{0} {1}',
          'Hour' => '{0} ({2}: {1})',
          'Minute' => '{0} ({2}: {1})',
          'Month' => '{0} ({2}: {1})',
          'Quarter' => '{0} ({2}: {1})',
          'Second' => '{0} ({2}: {1})',
          'Timezone' => '{0} {1}',
          'Week' => '{0} ({2}: {1})',
          'Year' => '{0} {1}',
        ),
      ),
    ),
    'gregorian' => 
    array (
      'months' => 
      array (
        'default' => 'format',
        'format' => 
        array (
          'default' => 'wide',
          'abbreviated' => 
          array (
            1 => 'Jan',
            2 => 'Feb',
            3 => 'Mar',
            4 => 'Apr',
            5 => 'May',
            6 => 'Jun',
            7 => 'Jul',
            8 => 'Aug',
            9 => 'Sep',
            10 => 'Oct',
            11 => 'Nov',
            12 => 'Dec',
          ),
          'wide' => 
          array (
            1 => 'January',
            2 => 'February',
            3 => 'March',
            4 => 'April',
            5 => 'May',
            6 => 'June',
            7 => 'July',
            8 => 'August',
            9 => 'September',
            10 => 'October',
            11 => 'November',
            12 => 'December',
          ),
        ),
        'stand-alone' => 
        array (
          'narrow' => 
          array (
            1 => 'J',
            2 => 'F',
            3 => 'M',
            4 => 'A',
            5 => 'M',
            6 => 'J',
            7 => 'J',
            8 => 'A',
            9 => 'S',
            10 => 'O',
            11 => 'N',
            12 => 'D',
          ),
        ),
      ),
      'days' => 
      array (
        'default' => 'format',
        'format' => 
        array (
          'default' => 'wide',
          'abbreviated' => 
          array (
            1 => 'Sun',
            2 => 'Mon',
            3 => 'Tue',
            4 => 'Wed',
            5 => 'Thu',
            6 => 'Fri',
            7 => 'Sat',
          ),
          'wide' => 
          array (
            1 => 'Sunday',
            2 => 'Monday',
            3 => 'Tuesday',
            4 => 'Wednesday',
            5 => 'Thursday',
            6 => 'Friday',
            7 => 'Saturday',
          ),
        ),
        'stand-alone' => 
        array (
          'narrow' => 
          array (
            1 => 'S',
            2 => 'M',
            3 => 'T',
            4 => 'W',
            5 => 'T',
            6 => 'F',
            7 => 'S',
          ),
        ),
      ),
      'quarters' => 
      array (
        'format' => 
        array (
          'abbreviated' => 
          array (
            1 => 'Q1',
            2 => 'Q2',
            3 => 'Q3',
            4 => 'Q4',
          ),
          'wide' => 
          array (
            1 => '1st quarter',
            2 => '2nd quarter',
            3 => '3rd quarter',
            4 => '4th quarter',
          ),
        ),
      ),
      'am' => 'AM',
      'pm' => 'PM',
      'eras' => 
      array (
        'wide' => 
        array (
          0 => 'Before Christ',
          1 => 'Anno Domini',
        ),
        'abbreviated' => 
        array (
          0 => 'BC',
          1 => 'AD',
        ),
      ),
      'dateFormats' => 
      array (
        'default' => 'medium',
        'full' => 
        array (
          'pattern' => 'EEEE, MMMM d, yyyy',
        ),
        'long' => 
        array (
          'pattern' => 'MMMM d, yyyy',
        ),
        'medium' => 
        array (
          'pattern' => 'MMM d, yyyy',
        ),
        'short' => 
        array (
          'pattern' => 'M/d/yy',
        ),
      ),
      'timeFormats' => 
      array (
        'default' => 'medium',
        'full' => 
        array (
          'pattern' => 'h:mm:ss a v',
        ),
        'long' => 
        array (
          'pattern' => 'h:mm:ss a z',
        ),
        'medium' => 
        array (
          'pattern' => 'h:mm:ss a',
        ),
        'short' => 
        array (
          'pattern' => 'h:mm a',
        ),
      ),
      'dateTimeFormats' => 
      array (
        'default' => '__default',
        'formats' => 
        array (
          '__default' => '{1} {0}',
        ),
        'availableFormats' => 
        array (
          'yyQ' => 'Q yy',
          'HHmm' => 'HH:mm',
          'HHmmss' => 'HH:mm:ss',
          'MMMMd' => 'MMMM d',
          'Md' => 'M/d',
          'mmss' => 'mm:ss',
          'yyMM' => 'MM/yy',
          'yyQQQQ' => 'QQQQ yy',
          'yyyyMMM' => 'MMM yyyy',
        ),
        'appendItems' => 
        array (
          'Day' => '{0} ({2}: {1})',
          'Day-Of-Week' => '{0} {1}',
          'Era' => '{0} {1}',
          'Hour' => '{0} ({2}: {1})',
          'Minute' => '{0} ({2}: {1})',
          'Month' => '{0} ({2}: {1})',
          'Quarter' => '{0} ({2}: {1})',
          'Second' => '{0} ({2}: {1})',
          'Timezone' => '{0} {1}',
          'Week' => '{0} ({2}: {1})',
          'Year' => '{0} {1}',
        ),
      ),
      'fields' => 
      array (
        'era' => 
        array (
          'displayName' => 'Era',
        ),
        'year' => 
        array (
          'displayName' => 'Year',
        ),
        'month' => 
        array (
          'displayName' => 'Month',
        ),
        'week' => 
        array (
          'displayName' => 'Week',
        ),
        'day' => 
        array (
          'displayName' => 'Day',
          'relatives' => 
          array (
            0 => 'Today',
            1 => 'Tomorrow',
            -1 => 'Yesterday',
          ),
        ),
        'weekday' => 
        array (
          'displayName' => 'Day of the Week',
        ),
        'dayperiod' => 
        array (
          'displayName' => 'AM/PM',
        ),
        'hour' => 
        array (
          'displayName' => 'Hour',
        ),
        'minute' => 
        array (
          'displayName' => 'Minute',
        ),
        'second' => 
        array (
          'displayName' => 'Second',
        ),
        'zone' => 
        array (
          'displayName' => 'Zone',
        ),
      ),
    ),
    'hebrew' => 
    array (
      'months' => 
      array (
        'default' => 'format',
        'format' => 
        array (
          'default' => 'wide',
          'abbreviated' => 
          array (
            1 => 'Tishri',
            2 => 'Heshvan',
            3 => 'Kislev',
            4 => 'Tevet',
            5 => 'Shevat',
            6 => 'Adar I',
            7 => 'Adar',
            8 => 'Nisan',
            9 => 'Iyar',
            10 => 'Sivan',
            11 => 'Tamuz',
            12 => 'Av',
            13 => 'Elul',
          ),
          'wide' => 
          array (
            1 => 'Tishri',
            2 => 'Heshvan',
            3 => 'Kislev',
            4 => 'Tevet',
            5 => 'Shevat',
            6 => 'Adar I',
            7 => 'Adar',
            8 => 'Nisan',
            9 => 'Iyar',
            10 => 'Sivan',
            11 => 'Tamuz',
            12 => 'Av',
            13 => 'Elul',
          ),
        ),
      ),
      'eras' => 
      array (
        'abbreviated' => 
        array (
          0 => 'AM',
        ),
      ),
    ),
    'islamic' => 
    array (
      'months' => 
      array (
        'default' => 'format',
        'format' => 
        array (
          'default' => 'wide',
          'abbreviated' => 
          array (
            1 => 'Muharram',
            2 => 'Safar',
            3 => 'Rabiʻ I',
            4 => 'Rabiʻ II',
            5 => 'Jumada I',
            6 => 'Jumada II',
            7 => 'Rajab',
            8 => 'Shaʻban',
            9 => 'Ramadan',
            10 => 'Shawwal',
            11 => 'Dhuʻl-Qiʻdah',
            12 => 'Dhuʻl-Hijjah',
          ),
          'wide' => 
          array (
            1 => 'Muharram',
            2 => 'Safar',
            3 => 'Rabiʻ I',
            4 => 'Rabiʻ II',
            5 => 'Jumada I',
            6 => 'Jumada II',
            7 => 'Rajab',
            8 => 'Shaʻban',
            9 => 'Ramadan',
            10 => 'Shawwal',
            11 => 'Dhuʻl-Qiʻdah',
            12 => 'Dhuʻl-Hijjah',
          ),
        ),
      ),
      'eras' => 
      array (
        'abbreviated' => 
        array (
          0 => 'AH',
        ),
      ),
      'dateFormats' => 
      array (
        'default' => 'medium',
        'full' => 
        array (
          'pattern' => 'EEEE, yyyy MMMM dd',
        ),
        'long' => 
        array (
          'pattern' => 'yyyy MMMM d',
        ),
        'medium' => 
        array (
          'pattern' => 'yyyy MMM d',
        ),
        'short' => 
        array (
          'pattern' => 'yy/MM/dd',
        ),
      ),
      'timeFormats' => 
      array (
        'default' => 'medium',
        'full' => 
        array (
          'pattern' => 'HH:mm:ss z',
        ),
        'long' => 
        array (
          'pattern' => 'HH:mm:ss z',
        ),
        'medium' => 
        array (
          'pattern' => 'HH:mm:ss',
        ),
        'short' => 
        array (
          'pattern' => 'HH:mm',
        ),
      ),
      'dateTimeFormats' => 
      array (
        'default' => '__default',
        'formats' => 
        array (
          '__default' => '{1} {0}',
        ),
        'availableFormats' => 
        array (
          'yyQ' => 'Q yy',
        ),
        'appendItems' => 
        array (
          'Day' => '{0} ({2}: {1})',
          'Day-Of-Week' => '{0} {1}',
          'Era' => '{0} {1}',
          'Hour' => '{0} ({2}: {1})',
          'Minute' => '{0} ({2}: {1})',
          'Month' => '{0} ({2}: {1})',
          'Quarter' => '{0} ({2}: {1})',
          'Second' => '{0} ({2}: {1})',
          'Timezone' => '{0} {1}',
          'Week' => '{0} ({2}: {1})',
          'Year' => '{0} {1}',
        ),
      ),
    ),
    'islamic-civil' => 
    array (
    ),
    'japanese' => 
    array (
      'eras' => 
      array (
        'abbreviated' => 
        array (
          0 => 'Taika',
          1 => 'Hakuchi',
          2 => 'Hakuhō',
          3 => 'Shuchō',
          4 => 'Taihō',
          5 => 'Keiun',
          6 => 'Wadō',
          7 => 'Reiki',
          8 => 'Yōrō',
          9 => 'Jinki',
          10 => 'Tempyō',
          11 => 'Tempyō-kampō',
          12 => 'Tempyō-shōhō',
          13 => 'Tempyō-hōji',
          14 => 'Temphō-jingo',
          15 => 'Jingo-keiun',
          16 => 'Hōki',
          17 => 'Ten-ō',
          18 => 'Enryaku',
          19 => 'Daidō',
          20 => 'Kōnin',
          21 => 'Tenchō',
          22 => 'Shōwa',
          23 => 'Kajō',
          24 => 'Ninju',
          25 => 'Saiko',
          26 => 'Tennan',
          27 => 'Jōgan',
          28 => 'Genkei',
          29 => 'Ninna',
          30 => 'Kampyō',
          31 => 'Shōtai',
          32 => 'Engi',
          33 => 'Enchō',
          34 => 'Shōhei',
          35 => 'Tengyō',
          36 => 'Tenryaku',
          37 => 'Tentoku',
          38 => 'Ōwa',
          39 => 'Kōhō',
          40 => 'Anna',
          41 => 'Tenroku',
          42 => 'Ten-en',
          43 => 'Jōgen',
          44 => 'Tengen',
          45 => 'Eikan',
          46 => 'Kanna',
          47 => 'Ei-en',
          48 => 'Eiso',
          49 => 'Shōryaku',
          50 => 'Chōtoku',
          51 => 'Chōhō',
          52 => 'Kankō',
          53 => 'Chōwa',
          54 => 'Kannin',
          55 => 'Jian',
          56 => 'Manju',
          57 => 'Chōgen',
          58 => 'Chōryaku',
          59 => 'Chōkyū',
          60 => 'Kantoku',
          61 => 'Eishō',
          62 => 'Tengi',
          63 => 'Kōhei',
          64 => 'Jiryaku',
          65 => 'Enkyū',
          66 => 'Shōho',
          67 => 'Shōryaku',
          68 => 'Eiho',
          69 => 'Ōtoku',
          70 => 'Kanji',
          71 => 'Kaho',
          72 => 'Eichō',
          73 => 'Shōtoku',
          74 => 'Kōwa',
          75 => 'Chōji',
          76 => 'Kashō',
          77 => 'Tennin',
          78 => 'Ten-ei',
          79 => 'Eikyū',
          80 => 'Gen-ei',
          81 => 'Hoan',
          82 => 'Tenji',
          83 => 'Daiji',
          84 => 'Tenshō',
          85 => 'Chōshō',
          86 => 'Hoen',
          87 => 'Eiji',
          88 => 'Kōji',
          89 => 'Tenyō',
          90 => 'Kyūan',
          91 => 'Ninpei',
          92 => 'Kyūju',
          93 => 'Hogen',
          94 => 'Heiji',
          95 => 'Eiryaku',
          96 => 'Ōho',
          97 => 'Chōkan',
          98 => 'Eiman',
          99 => 'Nin-an',
          100 => 'Kaō',
          101 => 'Shōan',
          102 => 'Angen',
          103 => 'Jishō',
          104 => 'Yōwa',
          105 => 'Juei',
          106 => 'Genryuku',
          107 => 'Bunji',
          108 => 'Kenkyū',
          109 => 'Shōji',
          110 => 'Kennin',
          111 => 'Genkyū',
          112 => 'Ken-ei',
          113 => 'Shōgen',
          114 => 'Kenryaku',
          115 => 'Kenpō',
          116 => 'Shōkyū',
          117 => 'Jōō',
          118 => 'Gennin',
          119 => 'Karoku',
          120 => 'Antei',
          121 => 'Kanki',
          122 => 'Jōei',
          123 => 'Tempuku',
          124 => 'Bunryaku',
          125 => 'Katei',
          126 => 'Ryakunin',
          127 => 'En-ō',
          128 => 'Ninji',
          129 => 'Kangen',
          130 => 'Hōji',
          131 => 'Kenchō',
          132 => 'Kōgen',
          133 => 'Shōka',
          134 => 'Shōgen',
          135 => 'Bun-ō',
          136 => 'Kōchō',
          137 => 'Bun-ei',
          138 => 'Kenji',
          139 => 'Kōan',
          140 => 'Shōō',
          141 => 'Einin',
          142 => 'Shōan',
          143 => 'Kengen',
          144 => 'Kagen',
          145 => 'Tokuji',
          146 => 'Enkei',
          147 => 'Ōchō',
          148 => 'Shōwa',
          149 => 'Bunpō',
          150 => 'Genō',
          151 => 'Genkyō',
          152 => 'Shōchū',
          153 => 'Kareki',
          154 => 'Gentoku',
          155 => 'Genkō',
          156 => 'Kemmu',
          157 => 'Engen',
          158 => 'Kōkoku',
          159 => 'Shōhei',
          160 => 'Kentoku',
          161 => 'Bunchũ',
          162 => 'Tenju',
          163 => 'Kōryaku',
          164 => 'Kōwa',
          165 => 'Genchũ',
          166 => 'Meitoku',
          167 => 'Kakei',
          168 => 'Kōō',
          169 => 'Meitoku',
          170 => 'Ōei',
          171 => 'Shōchō',
          172 => 'Eikyō',
          173 => 'Kakitsu',
          174 => 'Bun-an',
          175 => 'Hōtoku',
          176 => 'Kyōtoku',
          177 => 'Kōshō',
          178 => 'Chōroku',
          179 => 'Kanshō',
          180 => 'Bunshō',
          181 => 'Ōnin',
          182 => 'Bunmei',
          183 => 'Chōkyō',
          184 => 'Entoku',
          185 => 'Meiō',
          186 => 'Bunki',
          187 => 'Eishō',
          188 => 'Taiei',
          189 => 'Kyōroku',
          190 => 'Tenmon',
          191 => 'Kōji',
          192 => 'Eiroku',
          193 => 'Genki',
          194 => 'Tenshō',
          195 => 'Bunroku',
          196 => 'Keichō',
          197 => 'Genwa',
          198 => 'Kan-ei',
          199 => 'Shōho',
          200 => 'Keian',
          201 => 'Shōō',
          202 => 'Meiryaku',
          203 => 'Manji',
          204 => 'Kanbun',
          205 => 'Enpō',
          206 => 'Tenwa',
          207 => 'Jōkyō',
          208 => 'Genroku',
          209 => 'Hōei',
          210 => 'Shōtoku',
          211 => 'Kyōhō',
          212 => 'Genbun',
          213 => 'Kanpō',
          214 => 'Enkyō',
          215 => 'Kan-en',
          216 => 'Hōryaku',
          217 => 'Meiwa',
          218 => 'An-ei',
          219 => 'Tenmei',
          220 => 'Kansei',
          221 => 'Kyōwa',
          222 => 'Bunka',
          223 => 'Bunsei',
          224 => 'Tenpō',
          225 => 'Kōka',
          226 => 'Kaei',
          227 => 'Ansei',
          228 => 'Man-en',
          229 => 'Bunkyū',
          230 => 'Genji',
          231 => 'Keiō',
          232 => 'Meiji',
          233 => 'Taishō',
          234 => 'Shōwa',
          235 => 'Heisei',
        ),
        'narrow' => 
        array (
          232 => 'M',
          233 => 'T',
          234 => 'S',
          235 => 'H',
        ),
      ),
      'dateFormats' => 
      array (
        'default' => 'medium',
        'full' => 
        array (
          'pattern' => 'EEEE, MMMM d, y G',
        ),
        'long' => 
        array (
          'pattern' => 'MMMM d, y G',
        ),
        'medium' => 
        array (
          'pattern' => 'MMM d, y G',
        ),
        'short' => 
        array (
          'pattern' => 'M/d/yy',
        ),
      ),
      'timeFormats' => 
      array (
        'default' => 'medium',
        'full' => 
        array (
          'pattern' => 'HH:mm:ss z',
        ),
        'long' => 
        array (
          'pattern' => 'HH:mm:ss z',
        ),
        'medium' => 
        array (
          'pattern' => 'HH:mm:ss',
        ),
        'short' => 
        array (
          'pattern' => 'HH:mm',
        ),
      ),
      'dateTimeFormats' => 
      array (
        'default' => '__default',
        'formats' => 
        array (
          '__default' => '{1} {0}',
        ),
        'availableFormats' => 
        array (
          'yyQ' => 'Q yy',
        ),
        'appendItems' => 
        array (
          'Day' => '{0} ({2}: {1})',
          'Day-Of-Week' => '{0} {1}',
          'Era' => '{0} {1}',
          'Hour' => '{0} ({2}: {1})',
          'Minute' => '{0} ({2}: {1})',
          'Month' => '{0} ({2}: {1})',
          'Quarter' => '{0} ({2}: {1})',
          'Second' => '{0} ({2}: {1})',
          'Timezone' => '{0} {1}',
          'Week' => '{0} ({2}: {1})',
          'Year' => '{0} {1}',
        ),
      ),
    ),
    'persian' => 
    array (
      'months' => 
      array (
        'default' => 'format',
        'format' => 
        array (
          'default' => 'wide',
          'abbreviated' => 
          array (
            1 => 'Farvardin',
            2 => 'Ordibehesht',
            3 => 'Khordad',
            4 => 'Tir',
            5 => 'Mordad',
            6 => 'Shahrivar',
            7 => 'Mehr',
            8 => 'Aban',
            9 => 'Azar',
            10 => 'Dey',
            11 => 'Bahman',
            12 => 'Esfand',
          ),
          'wide' => 
          array (
            1 => 'Farvardin',
            2 => 'Ordibehesht',
            3 => 'Khordad',
            4 => 'Tir',
            5 => 'Mordad',
            6 => 'Shahrivar',
            7 => 'Mehr',
            8 => 'Aban',
            9 => 'Azar',
            10 => 'Dey',
            11 => 'Bahman',
            12 => 'Esfand',
          ),
        ),
      ),
      'eras' => 
      array (
        'abbreviated' => 
        array (
          0 => 'AP',
        ),
      ),
      'dateFormats' => 
      array (
        'default' => 'medium',
        'full' => 
        array (
          'pattern' => 'EEEE, yyyy MMMM dd',
        ),
        'long' => 
        array (
          'pattern' => 'yyyy MMMM d',
        ),
        'medium' => 
        array (
          'pattern' => 'yyyy MMM d',
        ),
        'short' => 
        array (
          'pattern' => 'yy/MM/dd',
        ),
      ),
      'timeFormats' => 
      array (
        'default' => 'medium',
        'full' => 
        array (
          'pattern' => 'HH:mm:ss z',
        ),
        'long' => 
        array (
          'pattern' => 'HH:mm:ss z',
        ),
        'medium' => 
        array (
          'pattern' => 'HH:mm:ss',
        ),
        'short' => 
        array (
          'pattern' => 'HH:mm',
        ),
      ),
      'dateTimeFormats' => 
      array (
        'default' => '__default',
        'formats' => 
        array (
          '__default' => '{1} {0}',
        ),
        'availableFormats' => 
        array (
          'yyQ' => 'Q yy',
        ),
        'appendItems' => 
        array (
          'Day' => '{0} ({2}: {1})',
          'Day-Of-Week' => '{0} {1}',
          'Era' => '{0} {1}',
          'Hour' => '{0} ({2}: {1})',
          'Minute' => '{0} ({2}: {1})',
          'Month' => '{0} ({2}: {1})',
          'Quarter' => '{0} ({2}: {1})',
          'Second' => '{0} ({2}: {1})',
          'Timezone' => '{0} {1}',
          'Week' => '{0} ({2}: {1})',
          'Year' => '{0} {1}',
        ),
      ),
    ),
  ),
  'timeZoneNames' => 
  array (
    'hourFormat' => '+HH:mm;-HH:mm',
    'hoursFormat' => '{0}/{1}',
    'gmtFormat' => 'GMT{0}',
    'regionFormat' => '{0}',
    'fallbackFormat' => '{0} ({1})',
    'abbreviationFallback' => 'standard',
    'singleCountries' => 
    array (
      0 => 'Africa/Bamako',
      1 => 'America/Godthab',
      2 => 'America/Santiago',
      3 => 'America/Guayaquil',
      4 => 'Asia/Shanghai',
      5 => 'Asia/Tashkent',
      6 => 'Asia/Kuala_Lumpur',
      7 => 'Europe/Madrid',
      8 => 'Europe/Lisbon',
      9 => 'Europe/London',
      10 => 'Pacific/Auckland',
      11 => 'Pacific/Tahiti',
    ),
    'zones' => 
    array (
      'America/Vancouver' => 
      array (
        'long' => 
        array (
          'generic' => 'Pacific Time (CA)',
          'standard' => 'Pacific Standard Time (CA)',
          'daylight' => 'Pacific Daylight Time (CA)',
        ),
        'short' => 
        array (
          'generic' => 'PT (CA)',
          'standard' => 'PST (CA)',
          'daylight' => 'PDT (CA)',
        ),
      ),
      'America/Edmonton' => 
      array (
        'long' => 
        array (
          'generic' => 'Mountain Time (CA)',
          'standard' => 'Mountain Standard Time (CA)',
          'daylight' => 'Mountain Daylight Time (CA)',
        ),
        'short' => 
        array (
          'generic' => 'MT (CA)',
          'standard' => 'MST (CA)',
          'daylight' => 'MDT (CA)',
        ),
      ),
      'America/Winnipeg' => 
      array (
        'long' => 
        array (
          'generic' => 'Central Time (CA)',
          'standard' => 'Central Standard Time (CA)',
          'daylight' => 'Central Daylight Time (CA)',
        ),
        'short' => 
        array (
          'generic' => 'CT (CA)',
          'standard' => 'CST (CA)',
          'daylight' => 'CDT (CA)',
        ),
      ),
      'America/Montreal' => 
      array (
        'long' => 
        array (
          'generic' => 'Eastern Time (CA)',
          'standard' => 'Eastern Standard Time (CA)',
          'daylight' => 'Eastern Daylight Time (CA)',
        ),
        'short' => 
        array (
          'generic' => 'ET (CA)',
          'standard' => 'EST (CA)',
          'daylight' => 'EDT (CA)',
        ),
      ),
      'America/Halifax' => 
      array (
        'long' => 
        array (
          'generic' => 'Atlantic Time',
          'standard' => 'Atlantic Standard Time',
          'daylight' => 'Atlantic Daylight Time',
        ),
        'short' => 
        array (
          'generic' => 'AT',
          'standard' => 'AST',
          'daylight' => 'ADT',
        ),
      ),
      'America/St_Johns' => 
      array (
        'long' => 
        array (
          'generic' => 'Newfoundland Time',
          'standard' => 'Newfoundland Standard Time',
          'daylight' => 'Newfoundland Daylight Time',
        ),
        'short' => 
        array (
          'generic' => 'NT',
          'standard' => 'NST',
          'daylight' => 'NDT',
        ),
        'exemplarCity' => 'St. John’s',
      ),
      'Asia/Shanghai' => 
      array (
        'long' => 
        array (
          'standard' => 'China Standard Time',
          'daylight' => 'China Daylight Time',
        ),
      ),
      'Europe/Paris' => 
      array (
        'long' => 
        array (
          'generic' => 'Central European Time',
          'standard' => 'Central European Standard Time',
          'daylight' => 'Central European Daylight Time',
        ),
        'short' => 
        array (
          'generic' => 'CET',
          'standard' => 'CEST',
          'daylight' => 'CEDT',
        ),
        'exemplarCity' => 'Paris',
      ),
      'Europe/London' => 
      array (
        'long' => 
        array (
          'standard' => 'Greenwich Mean Time',
          'daylight' => 'British Summer Time',
        ),
        'short' => 
        array (
          'standard' => 'GMT',
          'daylight' => 'BST',
        ),
      ),
      'Europe/Dublin' => 
      array (
        'long' => 
        array (
          'standard' => 'Greenwich Mean Time',
          'daylight' => 'Irish Summer Time',
        ),
        'short' => 
        array (
          'standard' => 'GMT',
          'daylight' => 'IST',
        ),
        'exemplarCity' => 'Dublin',
      ),
      'Asia/Jerusalem' => 
      array (
        'long' => 
        array (
          'standard' => 'Israel Standard Time',
          'daylight' => 'Israel Daylight Time',
        ),
        'exemplarCity' => 'Jerusalem',
      ),
      'Asia/Tokyo' => 
      array (
        'long' => 
        array (
          'standard' => 'Japan Standard Time',
          'daylight' => 'Japan Daylight Time',
        ),
        'short' => 
        array (
          'standard' => 'JST',
          'daylight' => 'JDT',
        ),
        'exemplarCity' => 'Tokyo',
      ),
      'Europe/Bucharest' => 
      array (
        'long' => 
        array (
          'standard' => 'Eastern European Standard Time',
          'daylight' => 'Eastern European Daylight Time',
        ),
        'short' => 
        array (
          'standard' => 'EET',
          'daylight' => 'EEST',
        ),
        'exemplarCity' => 'Bucharest',
      ),
      'Asia/Singapore' => 
      array (
        'long' => 
        array (
          'standard' => 'Singapore Standard Time',
          'daylight' => 'Singapore Standard Time',
        ),
        'short' => 
        array (
          'standard' => 'SST',
          'daylight' => 'SST',
        ),
        'exemplarCity' => 'Singapore',
      ),
      'Pacific/Honolulu' => 
      array (
        'long' => 
        array (
          'generic' => 'Hawaii Time',
          'standard' => 'Hawaii Standard Time',
          'daylight' => 'Hawaii Daylight Time',
        ),
        'short' => 
        array (
          'generic' => 'HT',
          'standard' => 'HST',
          'daylight' => 'HDT',
        ),
      ),
      'America/Anchorage' => 
      array (
        'long' => 
        array (
          'generic' => 'Alaska Time',
          'standard' => 'Alaska Standard Time',
          'daylight' => 'Alaska Daylight Time',
        ),
        'short' => 
        array (
          'generic' => 'AKT',
          'standard' => 'AKST',
        ),
      ),
      'America/Los_Angeles' => 
      array (
        'long' => 
        array (
          'generic' => 'Pacific Time',
          'standard' => 'Pacific Standard Time',
          'daylight' => 'Pacific Daylight Time',
        ),
        'short' => 
        array (
          'generic' => 'PT',
          'standard' => 'PST',
          'daylight' => 'PDT',
        ),
      ),
      'America/Denver' => 
      array (
        'long' => 
        array (
          'generic' => 'Mountain Time',
          'standard' => 'Mountain Standard Time',
          'daylight' => 'Mountain Daylight Time',
        ),
        'short' => 
        array (
          'generic' => 'MT',
          'standard' => 'MST',
          'daylight' => 'MDT',
        ),
      ),
      'America/Chicago' => 
      array (
        'long' => 
        array (
          'generic' => 'Central Time',
          'standard' => 'Central Standard Time',
          'daylight' => 'Central Daylight Time',
        ),
        'short' => 
        array (
          'generic' => 'CT',
          'standard' => 'CST',
          'daylight' => 'CDT',
        ),
      ),
      'America/New_York' => 
      array (
        'long' => 
        array (
          'generic' => 'Eastern Time',
          'standard' => 'Eastern Standard Time',
          'daylight' => 'Eastern Daylight Time',
        ),
        'short' => 
        array (
          'generic' => 'ET',
          'standard' => 'EST',
          'daylight' => 'EDT',
        ),
      ),
    ),
  ),
  'numbers' => 
  array (
    'symbols' => 
    array (
      'decimal' => '.',
      'group' => ',',
      'list' => ';',
      'percentSign' => '%',
      'nativeZeroDigit' => '0',
      'patternDigit' => '#',
      'plusSign' => '+',
      'minusSign' => '-',
      'exponential' => 'E',
      'perMille' => '‰',
      'infinity' => '∞',
      'nan' => 'NaN',
    ),
    'decimalFormats' => 
    array (
      '__default' => '#,##0.###',
    ),
    'scientificFormats' => 
    array (
      '__default' => '#E0',
    ),
    'percentFormats' => 
    array (
      '__default' => '#,##0%',
    ),
    'currencySpacing' => 
    array (
      'beforeCurrency' => 
      array (
        'currencyMatch' => '[:letter:]',
        'surroundingMatch' => '[:digit:]',
        'insertBetween' => ' ',
      ),
      'afterCurrency' => 
      array (
        'currencyMatch' => '[:letter:]',
        'surroundingMatch' => '[:digit:]',
        'insertBetween' => ' ',
      ),
    ),
    'currencyFormats' => 
    array (
      '__default' => '¤#,##0.00',
    ),
    'currencies' => 
    array (
      'EUR' => 
      array (
        'displayName' => 'Euro',
        'symbol' => '€',
      ),
      'GBP' => 
      array (
        'displayName' => 'British Pound Sterling',
        'symbol' => '£',
      ),
      'INR' => 
      array (
        'displayName' => 'Indian Rupee',
        'symbol' => 
        array (
          0 => '0≤Rs.',
          1 => '1≤Re.',
          2 => '1<Rs.',
        ),
      ),
      'ITL' => 
      array (
        'displayName' => 'Italian Lira',
        'symbol' => '₤',
      ),
      'JPY' => 
      array (
        'displayName' => 'Japanese Yen',
        'symbol' => '¥',
      ),
      'USD' => 
      array (
        'displayName' => 'US Dollar',
        'symbol' => 'US$',
      ),
      'ADP' => 
      array (
        'displayName' => 'Andorran Peseta',
      ),
      'AED' => 
      array (
        'displayName' => 'United Arab Emirates Dirham',
      ),
      'AFA' => 
      array (
        'displayName' => 'Afghani (1927-2002)',
      ),
      'AFN' => 
      array (
        'displayName' => 'Afghani',
        'symbol' => 'Af',
      ),
      'ALL' => 
      array (
        'displayName' => 'Albanian Lek',
        'symbol' => 'lek',
      ),
      'AMD' => 
      array (
        'displayName' => 'Armenian Dram',
        'symbol' => 'dram',
      ),
      'ANG' => 
      array (
        'displayName' => 'Netherlands Antillan Guilder',
        'symbol' => 'NA f.',
      ),
      'AOA' => 
      array (
        'displayName' => 'Angolan Kwanza',
      ),
      'AOK' => 
      array (
        'displayName' => 'Angolan Kwanza (1977-1990)',
      ),
      'AON' => 
      array (
        'displayName' => 'Angolan New Kwanza (1990-2000)',
      ),
      'AOR' => 
      array (
        'displayName' => 'Angolan Kwanza Reajustado (1995-1999)',
      ),
      'ARA' => 
      array (
        'displayName' => 'Argentine Austral',
      ),
      'ARP' => 
      array (
        'displayName' => 'Argentine Peso (1983-1985)',
      ),
      'ARS' => 
      array (
        'displayName' => 'Argentine Peso',
        'symbol' => 'Arg$',
      ),
      'ATS' => 
      array (
        'displayName' => 'Austrian Schilling',
      ),
      'AUD' => 
      array (
        'displayName' => 'Australian Dollar',
        'symbol' => '$A',
      ),
      'AWG' => 
      array (
        'displayName' => 'Aruban Guilder',
      ),
      'AZM' => 
      array (
        'displayName' => 'Azerbaijanian Manat (1993-2006)',
      ),
      'AZN' => 
      array (
        'displayName' => 'Azerbaijanian Manat',
      ),
      'BAD' => 
      array (
        'displayName' => 'Bosnia-Herzegovina Dinar',
      ),
      'BAM' => 
      array (
        'displayName' => 'Bosnia-Herzegovina Convertible Mark',
        'symbol' => 'KM',
      ),
      'BBD' => 
      array (
        'displayName' => 'Barbados Dollar',
        'symbol' => 'BDS$',
      ),
      'BDT' => 
      array (
        'displayName' => 'Bangladesh Taka',
        'symbol' => 'Tk',
      ),
      'BEC' => 
      array (
        'displayName' => 'Belgian Franc (convertible)',
      ),
      'BEF' => 
      array (
        'displayName' => 'Belgian Franc',
        'symbol' => 'BF',
      ),
      'BEL' => 
      array (
        'displayName' => 'Belgian Franc (financial)',
      ),
      'BGL' => 
      array (
        'displayName' => 'Bulgarian Hard Lev',
        'symbol' => 'lev',
      ),
      'BGN' => 
      array (
        'displayName' => 'Bulgarian New Lev',
      ),
      'BHD' => 
      array (
        'displayName' => 'Bahraini Dinar',
        'symbol' => 'BD',
      ),
      'BIF' => 
      array (
        'displayName' => 'Burundi Franc',
        'symbol' => 'Fbu',
      ),
      'BMD' => 
      array (
        'displayName' => 'Bermudan Dollar',
        'symbol' => 'Ber$',
      ),
      'BND' => 
      array (
        'displayName' => 'Brunei Dollar',
      ),
      'BOB' => 
      array (
        'displayName' => 'Boliviano',
        'symbol' => 'Bs',
      ),
      'BOP' => 
      array (
        'displayName' => 'Bolivian Peso',
      ),
      'BOV' => 
      array (
        'displayName' => 'Bolivian Mvdol',
      ),
      'BRB' => 
      array (
        'displayName' => 'Brazilian Cruzeiro Novo (1967-1986)',
      ),
      'BRC' => 
      array (
        'displayName' => 'Brazilian Cruzado',
      ),
      'BRE' => 
      array (
        'displayName' => 'Brazilian Cruzeiro (1990-1993)',
      ),
      'BRL' => 
      array (
        'displayName' => 'Brazilian Real',
        'symbol' => 'R$',
      ),
      'BRN' => 
      array (
        'displayName' => 'Brazilian Cruzado Novo',
      ),
      'BRR' => 
      array (
        'displayName' => 'Brazilian Cruzeiro',
      ),
      'BSD' => 
      array (
        'displayName' => 'Bahamian Dollar',
      ),
      'BTN' => 
      array (
        'displayName' => 'Bhutan Ngultrum',
        'symbol' => 'Nu',
      ),
      'BUK' => 
      array (
        'displayName' => 'Burmese Kyat',
      ),
      'BWP' => 
      array (
        'displayName' => 'Botswanan Pula',
      ),
      'BYB' => 
      array (
        'displayName' => 'Belarussian New Ruble (1994-1999)',
      ),
      'BYR' => 
      array (
        'displayName' => 'Belarussian Ruble',
        'symbol' => 'Rbl',
      ),
      'BZD' => 
      array (
        'displayName' => 'Belize Dollar',
        'symbol' => 'BZ$',
      ),
      'CAD' => 
      array (
        'displayName' => 'Canadian Dollar',
        'symbol' => 'Can$',
      ),
      'CDF' => 
      array (
        'displayName' => 'Congolese Franc Congolais',
      ),
      'CHE' => 
      array (
        'displayName' => 'WIR Euro',
      ),
      'CHF' => 
      array (
        'displayName' => 'Swiss Franc',
        'symbol' => 'SwF',
      ),
      'CHW' => 
      array (
        'displayName' => 'WIR Franc',
      ),
      'CLF' => 
      array (
        'displayName' => 'Chilean Unidades de Fomento',
      ),
      'CLP' => 
      array (
        'displayName' => 'Chilean Peso',
        'symbol' => 'Ch$',
      ),
      'CNY' => 
      array (
        'displayName' => 'Chinese Yuan Renminbi',
        'symbol' => 'Y',
      ),
      'COP' => 
      array (
        'displayName' => 'Colombian Peso',
        'symbol' => 'Col$',
      ),
      'COU' => 
      array (
        'displayName' => 'Unidad de Valor Real',
      ),
      'CRC' => 
      array (
        'displayName' => 'Costa Rican Colon',
        'symbol' => 'C',
      ),
      'CSD' => 
      array (
        'displayName' => 'Serbian Dinar',
      ),
      'CSK' => 
      array (
        'displayName' => 'Czechoslovak Hard Koruna',
      ),
      'CUP' => 
      array (
        'displayName' => 'Cuban Peso',
      ),
      'CVE' => 
      array (
        'displayName' => 'Cape Verde Escudo',
        'symbol' => 'CVEsc',
      ),
      'CYP' => 
      array (
        'displayName' => 'Cyprus Pound',
        'symbol' => '£C',
      ),
      'CZK' => 
      array (
        'displayName' => 'Czech Republic Koruna',
      ),
      'DDM' => 
      array (
        'displayName' => 'East German Ostmark',
      ),
      'DEM' => 
      array (
        'displayName' => 'Deutsche Mark',
      ),
      'DJF' => 
      array (
        'displayName' => 'Djibouti Franc',
        'symbol' => 'DF',
      ),
      'DKK' => 
      array (
        'displayName' => 'Danish Krone',
        'symbol' => 'DKr',
      ),
      'DOP' => 
      array (
        'displayName' => 'Dominican Peso',
        'symbol' => 'RD$',
      ),
      'DZD' => 
      array (
        'displayName' => 'Algerian Dinar',
        'symbol' => 'DA',
      ),
      'ECS' => 
      array (
        'displayName' => 'Ecuador Sucre',
      ),
      'ECV' => 
      array (
        'displayName' => 'Ecuador Unidad de Valor Constante (UVC)',
      ),
      'EEK' => 
      array (
        'displayName' => 'Estonian Kroon',
      ),
      'EGP' => 
      array (
        'displayName' => 'Egyptian Pound',
      ),
      'EQE' => 
      array (
        'displayName' => 'Ekwele',
      ),
      'ERN' => 
      array (
        'displayName' => 'Eritrean Nakfa',
      ),
      'ESA' => 
      array (
        'displayName' => 'Spanish Peseta (A account)',
      ),
      'ESB' => 
      array (
        'displayName' => 'Spanish Peseta (convertible account)',
      ),
      'ESP' => 
      array (
        'displayName' => 'Spanish Peseta',
        'symbol' => '₧',
      ),
      'ETB' => 
      array (
        'displayName' => 'Ethiopian Birr',
        'symbol' => 'Br',
      ),
      'FIM' => 
      array (
        'displayName' => 'Finnish Markka',
      ),
      'FJD' => 
      array (
        'displayName' => 'Fiji Dollar',
        'symbol' => 'F$',
      ),
      'FKP' => 
      array (
        'displayName' => 'Falkland Islands Pound',
      ),
      'FRF' => 
      array (
        'displayName' => 'French Franc',
      ),
      'GEK' => 
      array (
        'displayName' => 'Georgian Kupon Larit',
      ),
      'GEL' => 
      array (
        'displayName' => 'Georgian Lari',
        'symbol' => 'lari',
      ),
      'GHC' => 
      array (
        'displayName' => 'Ghana Cedi',
      ),
      'GIP' => 
      array (
        'displayName' => 'Gibraltar Pound',
      ),
      'GMD' => 
      array (
        'displayName' => 'Gambia Dalasi',
      ),
      'GNF' => 
      array (
        'displayName' => 'Guinea Franc',
        'symbol' => 'GF',
      ),
      'GNS' => 
      array (
        'displayName' => 'Guinea Syli',
      ),
      'GQE' => 
      array (
        'displayName' => 'Equatorial Guinea Ekwele Guineana',
      ),
      'GRD' => 
      array (
        'displayName' => 'Greek Drachma',
      ),
      'GTQ' => 
      array (
        'displayName' => 'Guatemala Quetzal',
        'symbol' => 'Q',
      ),
      'GWE' => 
      array (
        'displayName' => 'Portuguese Guinea Escudo',
      ),
      'GWP' => 
      array (
        'displayName' => 'Guinea-Bissau Peso',
      ),
      'GYD' => 
      array (
        'displayName' => 'Guyana Dollar',
        'symbol' => 'G$',
      ),
      'HKD' => 
      array (
        'displayName' => 'Hong Kong Dollar',
        'symbol' => 'HK$',
      ),
      'HNL' => 
      array (
        'displayName' => 'Hoduras Lempira',
        'symbol' => 'L',
      ),
      'HRD' => 
      array (
        'displayName' => 'Croatian Dinar',
      ),
      'HRK' => 
      array (
        'displayName' => 'Croatian Kuna',
      ),
      'HTG' => 
      array (
        'displayName' => 'Haitian Gourde',
      ),
      'HUF' => 
      array (
        'displayName' => 'Hungarian Forint',
        'symbol' => 'Ft',
      ),
      'IDR' => 
      array (
        'displayName' => 'Indonesian Rupiah',
        'symbol' => 'Rp',
      ),
      'IEP' => 
      array (
        'displayName' => 'Irish Pound',
        'symbol' => 'IR£',
      ),
      'ILP' => 
      array (
        'displayName' => 'Israeli Pound',
      ),
      'ILS' => 
      array (
        'displayName' => 'Israeli New Sheqel',
      ),
      'IQD' => 
      array (
        'displayName' => 'Iraqi Dinar',
        'symbol' => 'ID',
      ),
      'IRR' => 
      array (
        'displayName' => 'Iranian Rial',
        'symbol' => 'RI',
      ),
      'ISK' => 
      array (
        'displayName' => 'Icelandic Krona',
      ),
      'JMD' => 
      array (
        'displayName' => 'Jamaican Dollar',
        'symbol' => 'J$',
      ),
      'JOD' => 
      array (
        'displayName' => 'Jordanian Dinar',
        'symbol' => 'JD',
      ),
      'KES' => 
      array (
        'displayName' => 'Kenyan Shilling',
        'symbol' => 'K Sh',
      ),
      'KGS' => 
      array (
        'displayName' => 'Kyrgystan Som',
        'symbol' => 'som',
      ),
      'KHR' => 
      array (
        'displayName' => 'Cambodian Riel',
        'symbol' => 'CR',
      ),
      'KMF' => 
      array (
        'displayName' => 'Comoro Franc',
        'symbol' => 'CF',
      ),
      'KPW' => 
      array (
        'displayName' => 'North Korean Won',
      ),
      'KRW' => 
      array (
        'displayName' => 'South Korean Won',
      ),
      'KWD' => 
      array (
        'displayName' => 'Kuwaiti Dinar',
        'symbol' => 'KD',
      ),
      'KYD' => 
      array (
        'displayName' => 'Cayman Islands Dollar',
      ),
      'KZT' => 
      array (
        'displayName' => 'Kazakhstan Tenge',
        'symbol' => 'T',
      ),
      'LAK' => 
      array (
        'displayName' => 'Laotian Kip',
      ),
      'LBP' => 
      array (
        'displayName' => 'Lebanese Pound',
        'symbol' => 'LL',
      ),
      'LKR' => 
      array (
        'displayName' => 'Sri Lanka Rupee',
        'symbol' => 'SL Re',
      ),
      'LRD' => 
      array (
        'displayName' => 'Liberian Dollar',
      ),
      'LSL' => 
      array (
        'displayName' => 'Lesotho Loti',
        'symbol' => 'M',
      ),
      'LSM' => 
      array (
        'displayName' => 'Maloti',
      ),
      'LTL' => 
      array (
        'displayName' => 'Lithuanian Lita',
      ),
      'LTT' => 
      array (
        'displayName' => 'Lithuanian Talonas',
      ),
      'LUC' => 
      array (
        'displayName' => 'Luxembourg Convertible Franc',
      ),
      'LUF' => 
      array (
        'displayName' => 'Luxembourg Franc',
      ),
      'LUL' => 
      array (
        'displayName' => 'Luxembourg Financial Franc',
      ),
      'LVL' => 
      array (
        'displayName' => 'Latvian Lats',
      ),
      'LVR' => 
      array (
        'displayName' => 'Latvian Ruble',
      ),
      'LYD' => 
      array (
        'displayName' => 'Libyan Dinar',
        'symbol' => 'LD',
      ),
      'MAD' => 
      array (
        'displayName' => 'Moroccan Dirham',
      ),
      'MAF' => 
      array (
        'displayName' => 'Moroccan Franc',
      ),
      'MDL' => 
      array (
        'displayName' => 'Moldovan Leu',
      ),
      'MGA' => 
      array (
        'displayName' => 'Madagascar Ariary',
      ),
      'MGF' => 
      array (
        'displayName' => 'Madagascar Franc',
      ),
      'MKD' => 
      array (
        'displayName' => 'Macedonian Denar',
        'symbol' => 'MDen',
      ),
      'MLF' => 
      array (
        'displayName' => 'Mali Franc',
      ),
      'MMK' => 
      array (
        'displayName' => 'Myanmar Kyat',
      ),
      'MNT' => 
      array (
        'displayName' => 'Mongolian Tugrik',
        'symbol' => 'Tug',
      ),
      'MOP' => 
      array (
        'displayName' => 'Macao Pataca',
      ),
      'MRO' => 
      array (
        'displayName' => 'Mauritania Ouguiya',
        'symbol' => 'UM',
      ),
      'MTL' => 
      array (
        'displayName' => 'Maltese Lira',
        'symbol' => 'Lm',
      ),
      'MTP' => 
      array (
        'displayName' => 'Maltese Pound',
      ),
      'MUR' => 
      array (
        'displayName' => 'Mauritius Rupee',
      ),
      'MVR' => 
      array (
        'displayName' => 'Maldive Islands Rufiyaa',
      ),
      'MWK' => 
      array (
        'displayName' => 'Malawi Kwacha',
        'symbol' => 'MK',
      ),
      'MXN' => 
      array (
        'displayName' => 'Mexican Peso',
        'symbol' => 'MEX$',
      ),
      'MXP' => 
      array (
        'displayName' => 'Mexican Silver Peso (1861-1992)',
      ),
      'MXV' => 
      array (
        'displayName' => 'Mexican Unidad de Inversion (UDI)',
      ),
      'MYR' => 
      array (
        'displayName' => 'Malaysian Ringgit',
        'symbol' => 'RM',
      ),
      'MZE' => 
      array (
        'displayName' => 'Mozambique Escudo',
      ),
      'MZM' => 
      array (
        'displayName' => 'Old Mozambique Metical',
        'symbol' => 'Mt',
      ),
      'MZN' => 
      array (
        'displayName' => 'Mozambique Metical',
        'symbol' => 'MTn',
      ),
      'NAD' => 
      array (
        'displayName' => 'Namibia Dollar',
        'symbol' => 'N$',
      ),
      'NGN' => 
      array (
        'displayName' => 'Nigerian Naira',
      ),
      'NIC' => 
      array (
        'displayName' => 'Nicaraguan Cordoba',
      ),
      'NIO' => 
      array (
        'displayName' => 'Nicaraguan Cordoba Oro',
      ),
      'NLG' => 
      array (
        'displayName' => 'Netherlands Guilder',
      ),
      'NOK' => 
      array (
        'displayName' => 'Norwegian Krone',
        'symbol' => 'NKr',
      ),
      'NPR' => 
      array (
        'displayName' => 'Nepalese Rupee',
        'symbol' => 'Nrs',
      ),
      'NZD' => 
      array (
        'displayName' => 'New Zealand Dollar',
        'symbol' => '$NZ',
      ),
      'OMR' => 
      array (
        'displayName' => 'Oman Rial',
        'symbol' => 'RO',
      ),
      'PAB' => 
      array (
        'displayName' => 'Panamanian Balboa',
      ),
      'PEI' => 
      array (
        'displayName' => 'Peruvian Inti',
      ),
      'PEN' => 
      array (
        'displayName' => 'Peruvian Sol Nuevo',
      ),
      'PES' => 
      array (
        'displayName' => 'Peruvian Sol',
      ),
      'PGK' => 
      array (
        'displayName' => 'Papua New Guinea Kina',
      ),
      'PHP' => 
      array (
        'displayName' => 'Philippine Peso',
        'symbol' => 'Php',
      ),
      'PKR' => 
      array (
        'displayName' => 'Pakistan Rupee',
        'symbol' => 'Pra',
      ),
      'PLN' => 
      array (
        'displayName' => 'Polish Zloty',
        'symbol' => 'Zl',
      ),
      'PLZ' => 
      array (
        'displayName' => 'Polish Zloty (1950-1995)',
      ),
      'PTE' => 
      array (
        'displayName' => 'Portuguese Escudo',
      ),
      'PYG' => 
      array (
        'displayName' => 'Paraguay Guarani',
      ),
      'QAR' => 
      array (
        'displayName' => 'Qatari Rial',
        'symbol' => 'QR',
      ),
      'RHD' => 
      array (
        'displayName' => 'Rhodesian Dollar',
      ),
      'ROL' => 
      array (
        'displayName' => 'Old Romanian Leu',
        'symbol' => '=0#Old lei|1#Old leu|1<Old lei',
      ),
      'RON' => 
      array (
        'displayName' => 'Romanian Leu',
        'symbol' => '=0#lei|1#leu|1<lei',
      ),
      'RUB' => 
      array (
        'displayName' => 'Russian Ruble',
      ),
      'RUR' => 
      array (
        'displayName' => 'Russian Ruble (1991-1998)',
      ),
      'RWF' => 
      array (
        'displayName' => 'Rwandan Franc',
      ),
      'SAR' => 
      array (
        'displayName' => 'Saudi Riyal',
        'symbol' => 'SRl',
      ),
      'SBD' => 
      array (
        'displayName' => 'Solomon Islands Dollar',
        'symbol' => 'SI$',
      ),
      'SCR' => 
      array (
        'displayName' => 'Seychelles Rupee',
        'symbol' => 'SR',
      ),
      'SDD' => 
      array (
        'displayName' => 'Sudanese Dinar',
      ),
      'SDP' => 
      array (
        'displayName' => 'Sudanese Pound',
      ),
      'SEK' => 
      array (
        'displayName' => 'Swedish Krona',
        'symbol' => 'SKr',
      ),
      'SGD' => 
      array (
        'displayName' => 'Singapore Dollar',
        'symbol' => 'S$',
      ),
      'SHP' => 
      array (
        'displayName' => 'Saint Helena Pound',
      ),
      'SIT' => 
      array (
        'displayName' => 'Slovenia Tolar',
      ),
      'SKK' => 
      array (
        'displayName' => 'Slovak Koruna',
        'symbol' => 'Sk',
      ),
      'SLL' => 
      array (
        'displayName' => 'Sierra Leone Leone',
      ),
      'SOS' => 
      array (
        'displayName' => 'Somali Shilling',
        'symbol' => 'So. Sh.',
      ),
      'SRD' => 
      array (
        'displayName' => 'Surinam Dollar',
      ),
      'SRG' => 
      array (
        'displayName' => 'Suriname Guilder',
        'symbol' => 'Sf',
      ),
      'STD' => 
      array (
        'displayName' => 'Sao Tome and Principe Dobra',
        'symbol' => 'Db',
      ),
      'SUR' => 
      array (
        'displayName' => 'Soviet Rouble',
      ),
      'SVC' => 
      array (
        'displayName' => 'El Salvador Colon',
      ),
      'SYP' => 
      array (
        'displayName' => 'Syrian Pound',
        'symbol' => 'LS',
      ),
      'SZL' => 
      array (
        'displayName' => 'Swaziland Lilangeni',
        'symbol' => 'E',
      ),
      'THB' => 
      array (
        'displayName' => 'Thai Baht',
      ),
      'TJR' => 
      array (
        'displayName' => 'Tajikistan Ruble',
      ),
      'TJS' => 
      array (
        'displayName' => 'Tajikistan Somoni',
      ),
      'TMM' => 
      array (
        'displayName' => 'Turkmenistan Manat',
      ),
      'TND' => 
      array (
        'displayName' => 'Tunisian Dinar',
      ),
      'TOP' => 
      array (
        'displayName' => 'Tonga Paʻanga',
        'symbol' => 'T$',
      ),
      'TPE' => 
      array (
        'displayName' => 'Timor Escudo',
      ),
      'TRL' => 
      array (
        'displayName' => 'Turkish Lira',
        'symbol' => 'TL',
      ),
      'TRY' => 
      array (
        'displayName' => 'New Turkish Lira',
      ),
      'TTD' => 
      array (
        'displayName' => 'Trinidad and Tobago Dollar',
        'symbol' => 'TT$',
      ),
      'TWD' => 
      array (
        'displayName' => 'Taiwan New Dollar',
        'symbol' => 'NT$',
      ),
      'TZS' => 
      array (
        'displayName' => 'Tanzanian Shilling',
        'symbol' => 'T Sh',
      ),
      'UAH' => 
      array (
        'displayName' => 'Ukrainian Hryvnia',
      ),
      'UAK' => 
      array (
        'displayName' => 'Ukrainian Karbovanetz',
      ),
      'UGS' => 
      array (
        'displayName' => 'Ugandan Shilling (1966-1987)',
      ),
      'UGX' => 
      array (
        'displayName' => 'Ugandan Shilling',
        'symbol' => 'U Sh',
      ),
      'USN' => 
      array (
        'displayName' => 'US Dollar (Next day)',
      ),
      'USS' => 
      array (
        'displayName' => 'US Dollar (Same day)',
      ),
      'UYP' => 
      array (
        'displayName' => 'Uruguay Peso (1975-1993)',
      ),
      'UYU' => 
      array (
        'displayName' => 'Uruguay Peso Uruguayo',
        'symbol' => 'Ur$',
      ),
      'UZS' => 
      array (
        'displayName' => 'Uzbekistan Sum',
      ),
      'VEB' => 
      array (
        'displayName' => 'Venezuelan Bolivar',
        'symbol' => 'Be',
      ),
      'VND' => 
      array (
        'displayName' => 'Vietnamese Dong',
      ),
      'VUV' => 
      array (
        'displayName' => 'Vanuatu Vatu',
        'symbol' => 'VT',
      ),
      'WST' => 
      array (
        'displayName' => 'Western Samoa Tala',
      ),
      'XAF' => 
      array (
        'displayName' => 'CFA Franc BEAC',
      ),
      'XAG' => 
      array (
        'displayName' => 'Silver',
      ),
      'XAU' => 
      array (
        'displayName' => 'Gold',
      ),
      'XBA' => 
      array (
        'displayName' => 'European Composite Unit',
      ),
      'XBB' => 
      array (
        'displayName' => 'European Monetary Unit',
      ),
      'XBC' => 
      array (
        'displayName' => 'European Unit of Account (XBC)',
      ),
      'XBD' => 
      array (
        'displayName' => 'European Unit of Account (XBD)',
      ),
      'XCD' => 
      array (
        'displayName' => 'East Caribbean Dollar',
        'symbol' => 'EC$',
      ),
      'XDR' => 
      array (
        'displayName' => 'Special Drawing Rights',
      ),
      'XEU' => 
      array (
        'displayName' => 'European Currency Unit',
      ),
      'XFO' => 
      array (
        'displayName' => 'French Gold Franc',
      ),
      'XFU' => 
      array (
        'displayName' => 'French UIC-Franc',
      ),
      'XOF' => 
      array (
        'displayName' => 'CFA Franc BCEAO',
      ),
      'XPD' => 
      array (
        'displayName' => 'Palladium',
      ),
      'XPF' => 
      array (
        'displayName' => 'CFP Franc',
        'symbol' => 'CFPF',
      ),
      'XPT' => 
      array (
        'displayName' => 'Platinum',
      ),
      'XRE' => 
      array (
        'displayName' => 'RINET Funds',
      ),
      'XTS' => 
      array (
        'displayName' => 'Testing Currency Code',
      ),
      'XXX' => 
      array (
        'displayName' => 'No Currency',
      ),
      'YDD' => 
      array (
        'displayName' => 'Yemeni Dinar',
      ),
      'YER' => 
      array (
        'displayName' => 'Yemeni Rial',
        'symbol' => 'YRl',
      ),
      'YUD' => 
      array (
        'displayName' => 'Yugoslavian Hard Dinar',
      ),
      'YUM' => 
      array (
        'displayName' => 'Yugoslavian Noviy Dinar',
      ),
      'YUN' => 
      array (
        'displayName' => 'Yugoslavian Convertible Dinar',
      ),
      'ZAL' => 
      array (
        'displayName' => 'South African Rand (financial)',
      ),
      'ZAR' => 
      array (
        'displayName' => 'South African Rand',
        'symbol' => 'R',
      ),
      'ZMK' => 
      array (
        'displayName' => 'Zambian Kwacha',
      ),
      'ZRN' => 
      array (
        'displayName' => 'Zairean New Zaire',
      ),
      'ZRZ' => 
      array (
        'displayName' => 'Zairean Zaire',
      ),
      'ZWD' => 
      array (
        'displayName' => 'Zimbabwe Dollar',
        'symbol' => 'Z$',
      ),
    ),
  ),
);

?>