<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/LConf/validate/Interface/ActionBar/filterList.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2011-09-02T13:02:14+0000

${'_validator_eventId'} = new AgaviStringValidator();
${'_validator_eventId'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => true,
  'class' => 'string',
  'name' => 'eventId',
), array (
  0 => 'eventId',
), array (
  '' => 'Validation of parameter "eventId" failed',
));
${'validationManager'}->addChild(${'_validator_eventId'});
${'_validator_parentid'} = new AgaviStringValidator();
${'_validator_parentid'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => true,
  'class' => 'string',
  'name' => 'parentid',
), array (
  0 => 'parentid',
), array (
  '' => 'Validation of parameter "parentid" failed',
));
${'validationManager'}->addChild(${'_validator_parentid'});

?>