<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/AppKit/validate/Widgets/HeaderData.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2011-09-02T13:02:10+0000

${'_validator_type'} = new AgaviStringValidator();
${'_validator_type'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => false,
  'name' => 'type',
  'class' => 'string',
), array (
  0 => 'type',
), array (
));
${'validationManager'}->addChild(${'_validator_type'});

?>