<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/AppKit/validate/Ext/initI18n.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2011-09-02T13:02:12+0000



?>