<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/config/javascript.xml
// Generated by: AppKitResourceConfigHandler
// Date: 2011-09-02T13:02:10+0000

$this->resources = array_merge_recursive($this->resources, array (
  'javascript' => 
  array (
    0 => '/usr/local/lconf-standalone/lib/ext3/adapter/ext/ext-base.js',
    1 => '/usr/local/lconf-standalone/lib/ext3/ext-all-debug.js',
    2 => '/usr/local/lconf-standalone/app/modules/AppKit/lib/js/AppKit.js',
    3 => '/usr/local/lconf-standalone/app/modules/AppKit/lib/js/AppKitUtil.js',
    4 => '/usr/local/lconf-standalone/app/modules/AppKit/lib/js/utils/stacktrace.js',
    5 => '/usr/local/lconf-standalone/app/modules/AppKit/lib/js/utils/AppKitServertime.js',
    6 => '/usr/local/lconf-standalone/app/modules/AppKit/lib/js/AppKitErrorHandler.js',
    7 => '/usr/local/lconf-standalone/app/modules/AppKit/lib/js/Layout.js',
    8 => '/usr/local/lconf-standalone/app/modules/AppKit/lib/js/AppKitNavBar.js',
    9 => '/usr/local/lconf-standalone/app/modules/AppKit/lib/js/utils/HttpStateProvider.js',
    10 => '/usr/local/lconf-standalone/app/modules/AppKit/lib/js/form/action/JSONSubmit.js',
    11 => '/usr/local/lconf-standalone/app/modules/AppKit/lib/js/request/Ajax.js',
    12 => '/usr/local/lconf-standalone/app/modules/AppKit/lib/js/ux/DDTabPanel.js',
    13 => '/usr/local/lconf-standalone/lib/jsgettext/lib/Gettext.js',
    14 => '/usr/local/lconf-standalone/app/modules/LConf/lib/js/GridTreeEditorField.js',
    15 => '/usr/local/lconf-standalone/app/modules/LConf/lib/js/MultiSelectTree.js',
    16 => '/usr/local/lconf-standalone/app/modules/LConf/lib/js/ldapColumn.js',
  ),
  'css' => 
  array (
  ),
  'css_import' => 
  array (
  ),
));
$this->jactions=array_merge_recursive($this->jactions, array (
  0 => 
  array (
    'module' => 'AppKit',
    'action' => 'Ext.initI18n',
    'output_type' => 'javascript',
  ),
));

?>