<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/LConf/validate/Backend/listFilters.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2011-09-02T13:02:15+0000



?>