<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/config/logging.xml
// Generated by: AgaviLoggingConfigHandler
// Date: 2011-09-02T13:02:09+0000

${'_layout_DateTimeLayout'} = new AgaviTimestampLoggerLayout();
${'_layout_DateTimeLayout'}->initialize($this->context, array (
));
${'_layout_PassThru'} = new AgaviPassthruLoggerLayout();
${'_layout_PassThru'}->initialize($this->context, array (
));
${'_layout_ApacheStyle'} = new AppKitApacheLoggerFormat();
${'_layout_ApacheStyle'}->initialize($this->context, array (
));
${'_appender_AppKitDoctrineLogAppender'} = new AppKitDoctrineLoggerAppender();
${'_appender_AppKitDoctrineLogAppender'}->initialize($this->context, array (
));
${'_appender_AppKitDoctrineLogAppender'}->setLayout(${'_layout_PassThru'});
${'_appender_UniversalLogfileAppender'} = new AgaviRotatingFileLoggerAppender();
${'_appender_UniversalLogfileAppender'}->initialize($this->context, array (
  'dir' => '/usr/local/lconf-standalone/log/',
  'prefix' => 'icinga-web-',
));
${'_appender_UniversalLogfileAppender'}->setLayout(${'_layout_ApacheStyle'});
${'_appender_DebugLogfileAppender'} = new AgaviRotatingFileLoggerAppender();
${'_appender_DebugLogfileAppender'}->initialize($this->context, array (
  'dir' => '/usr/local/lconf-standalone/log/',
  'prefix' => 'debug-',
));
${'_appender_DebugLogfileAppender'}->setLayout(${'_layout_ApacheStyle'});
${'_appender_StdErrorAppender'} = new AgaviStderrLoggerAppender();
${'_appender_StdErrorAppender'}->initialize($this->context, array (
));
${'_appender_StdErrorAppender'}->setLayout(${'_layout_DateTimeLayout'});
${'_logger_icinga-web'} = new AgaviLogger();
${'_logger_icinga-web'}->setAppender('UniversalLogfileAppender', ${'_appender_UniversalLogfileAppender'});
${'_logger_icinga-web'}->setLevel(AgaviLogger::ALL ^ AgaviLogger::DEBUG ^ AgaviLogger::INFO);
$this->setLogger('icinga-web', ${'_logger_icinga-web'});
${'_logger_icinga-debug'} = new AgaviLogger();
${'_logger_icinga-debug'}->setAppender('DebugLogfileAppender', ${'_appender_DebugLogfileAppender'});
${'_logger_icinga-debug'}->setLevel(AgaviLogger::ALL );
$this->setLogger('icinga-debug', ${'_logger_icinga-debug'});
${'_logger_appkit-database'} = new AgaviLogger();
${'_logger_appkit-database'}->setAppender('AppKitDoctrineLogAppender', ${'_appender_AppKitDoctrineLogAppender'});
${'_logger_appkit-database'}->setLevel(AgaviLogger::ALL ^ AgaviLogger::DEBUG ^ AgaviLogger::INFO);
$this->setLogger('appkit-database', ${'_logger_appkit-database'});
$this->setDefaultLoggerName('icinga-web');

?>