<?php

// This is a compiled Agavi configuration file
// Compiled from: (unknown)
// Generated by: AppKitMenuConfigHandler
// Date: 2011-09-02T13:02:10+0000

return array (
  0 => 
  array (
    'id' => 'menu_lconf',
    'credential' => 'lconf.user',
    'icon' => 'lconf-logo',
    'caption' => 'LDAP Editor',
    'target' => 
    array (
      'url' => '/lconf/modules/lconf/',
      'target' => 'new',
    ),
  ),
  1 => 
  array (
    'id' => 'menu_lconf_connectionmgr',
    'icon' => 'icinga-icon-user',
    'caption' => 'Connections',
    'target' => 
    array (
      'url' => '/lconf/modules/lconf/admin',
      'target' => 'new',
    ),
  ),
  2 => 
  array (
    'id' => 'menu_admin',
    'credential' => 'lconf.user;appkit.admin',
    'icon' => 'icinga-icon-wrench',
    'caption' => 'Admin',
    'items' => 
    array (
      0 => 
      array (
        'credential' => 'appkit.admin.users',
        'icon' => 'icinga-icon-user',
        'caption' => 'Users',
        'target' => 
        array (
          'url' => '/lconf/modules/appkit/admin/users',
          'target' => 'new',
        ),
      ),
      1 => 
      array (
        'credential' => 'appkit.admin.groups',
        'icon' => 'icinga-icon-group',
        'caption' => 'Groups',
        'target' => 
        array (
          'url' => '/lconf/modules/appkit/admin/groups',
          'target' => 'new',
        ),
      ),
    ),
  ),
  3 => 
  array (
    'id' => 'menu_lconf_about',
    'icon' => 'icinga-icon-help',
    'caption' => 'About',
    'target' => 
    array (
      'url' => '/lconf/modules/lconf/about',
      'target' => 'window',
      'title' => 'About lconf',
      'id' => 'icinga-window-lconf-about',
    ),
  ),
)

?>