<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/LConf/config/module.xml
// Generated by: AgaviModuleConfigHandler
// Date: 2011-09-02T13:02:09+0000

$lcModuleName = strtolower($moduleName);
AgaviConfig::set(AgaviToolkit::expandVariables('modules.${moduleName}.enabled', array('moduleName' => $lcModuleName)), true, true, true);
$moduleConfig = array (
  'modules.${moduleName}.title' => 'Lconf Module',
  'modules.${moduleName}.version' => '1.0.1',
  'modules.${moduleName}.connectionSource' => 'DB',
  'modules.${moduleName}.appkit_module.app.css_files' => 
  array (
    0 => '/styles/icinga_lconf.css',
  ),
  'modules.${moduleName}.appkit_module.app.javascript_files' => 
  array (
    0 => '/usr/local/lconf-standalone/app/modules/LConf/lib/js/MultiSelectTree.js',
    1 => '/usr/local/lconf-standalone/app/modules/LConf/lib/js/GridTreeEditorField.js',
  ),
  'modules.${moduleName}.icons' => 
  array (
    'organizationalUnit' => 'icinga-icon-organisation',
    'lconfStructuralObject' => 'lconf-logo',
    'lconfTimeperiod' => 'icinga-icon-clock-red',
    'lconfCommand' => 'icinga-icon-script',
    'lconfContact' => 'icinga-icon-user',
    'lconfContactgroup' => 'icinga-icon-group',
    'lconfHost' => 'icinga-icon-server',
    'lconfHostgroup' => 'icinga-icon-hostgroup',
    'lconfService' => 'icinga-icon-cog',
    'lconfServicegroup' => 'icinga-object-servicegroup',
    'alias' => 'icinga-icon-attach',
  ),
  'modules.${moduleName}.prefix' => '@@SCHEMA_PREFIX@@',
  'modules.${moduleName}.customDialogs' => 
  array (
    0 => 
    array (
      'view' => 'Command',
      'description' => 'Create a Command',
      'iconCls' => 'icinga-icon-script',
    ),
    1 => 
    array (
      'view' => 'Timeperiod',
      'description' => 'Create a Timeperiod',
      'iconCls' => 'icinga-icon-clock-red',
    ),
    2 => 
    array (
      'view' => 'Contact',
      'description' => 'Create a Contact',
      'iconCls' => 'icinga-icon-user',
    ),
    3 => 
    array (
      'view' => 'Contactgroup',
      'description' => 'Create a Contactgroup',
      'iconCls' => 'icinga-icon-group',
    ),
    4 => 
    array (
      'view' => 'Host',
      'description' => 'Create a Host',
      'iconCls' => 'icinga-icon-server',
    ),
    5 => 
    array (
      'view' => 'Hostgroup',
      'description' => 'Create a Hostgroup',
      'iconCls' => 'icinga-icon-hostgroup',
    ),
    6 => 
    array (
      'view' => 'Service',
      'description' => 'Create a Service',
      'iconCls' => 'icinga-icon-cog',
    ),
    7 => 
    array (
      'view' => 'Servicegroup',
      'description' => 'Create a Servicegroup',
      'iconCls' => 'icinga-object-servicegroup',
    ),
    8 => 
    array (
      'view' => 'StructuralObject',
      'description' => 'Create a Structural Object',
      'iconCls' => 'lconf-logo',
    ),
    9 => 
    array (
      'view' => 'Default',
      'description' => 'Custom entry',
      'iconCls' => 'icinga-icon-bricks',
    ),
  ),
  'modules.${moduleName}.propertyPresets' => 
  array (
    'property' => 
    array (
      'factory' => 'ComboBox',
      'parameter' => '"properties"',
    ),
    'objectclass' => 
    array (
      'factory' => 'ComboBox',
      'parameter' => '"objectclass"',
    ),
    '@@SCHEMA_PREFIX@@ContactHostNotificationPeriod' => 
    array (
      'factory' => 'ComboBox',
      'parameter' => '{"LDAP":["objectclass=@@SCHEMA_PREFIX@@Timeperiod"],"Attr": "cn"}',
    ),
    '@@SCHEMA_PREFIX@@Members' => 
    array (
      '@@SCHEMA_PREFIX@@HostGroup' => 
      array (
        'factory' => 'Set',
        'parameter' => '{"LDAP":["objectclass=@@SCHEMA_PREFIX@@Host"],"Attr": "cn"}',
      ),
      '@@SCHEMA_PREFIX@@ServiceGroup' => 
      array (
        'factory' => 'Set',
        'parameter' => '{"LDAP":["objectclass=@@SCHEMA_PREFIX@@Service"],"Attr": "cn"}',
      ),
      '@@SCHEMA_PREFIX@@ContactGroup' => 
      array (
        'factory' => 'Set',
        'parameter' => '{"LDAP":["objectclass=@@SCHEMA_PREFIX@@Contact"],"Attr": "cn"}',
      ),
      'factory' => 'Set',
      'parameter' => '{"LDAP":["objectclass=@@SCHEMA_PREFIX@@Host"],"Attr": "cn"}',
    ),
    '@@SCHEMA_PREFIX@@ContactHostNotificationCommands' => 
    array (
      'factory' => 'ComboBox',
      'parameter' => '{"LDAP":["objectclass=@@SCHEMA_PREFIX@@Command"],"Attr": "cn"}',
    ),
    '@@SCHEMA_PREFIX@@ContactServiceNotificationPeriod' => 
    array (
      'factory' => 'ComboBox',
      'parameter' => '{"LDAP":["objectclass=@@SCHEMA_PREFIX@@Timeperiod"],"Attr": "cn"}',
    ),
    '@@SCHEMA_PREFIX@@ContactServiceNotificationCommands' => 
    array (
      'factory' => 'ComboBox',
      'parameter' => '{"LDAP":["objectclass=@@SCHEMA_PREFIX@@Command"],"Attr": "cn"}',
    ),
    '@@SCHEMA_PREFIX@@HostNotificationPeriod' => 
    array (
      'factory' => 'ComboBox',
      'parameter' => '{"LDAP":["objectclass=@@SCHEMA_PREFIX@@Timeperiod"],"Attr": "cn"}',
    ),
    '@@SCHEMA_PREFIX@@HostCheckPeriod' => 
    array (
      'factory' => 'ComboBox',
      'parameter' => '{"LDAP":["objectclass=@@SCHEMA_PREFIX@@Timeperiod"],"Attr": "cn"}',
    ),
    '@@SCHEMA_PREFIX@@Checkcommand' => 
    array (
      'factory' => 'ComboBox',
      'parameter' => '{"LDAP":["objectclass=@@SCHEMA_PREFIX@@Command"],"Attr": "cn"}',
    ),
    '@@SCHEMA_PREFIX@@HostDependency' => 
    array (
      'factory' => 'ComboBox',
      'parameter' => '{"LDAP":["objectclass=@@SCHEMA_PREFIX@@Host"],"Attr": "cn"}',
    ),
    '@@SCHEMA_PREFIX@@ServiceNotificationPeriod' => 
    array (
      'factory' => 'ComboBox',
      'parameter' => '{"LDAP":["objectclass=@@SCHEMA_PREFIX@@Timeperiod"],"Attr": "cn"}',
    ),
    '@@SCHEMA_PREFIX@@ServiceCheckPeriod' => 
    array (
      'factory' => 'ComboBox',
      'parameter' => '{"LDAP":["objectclass=@@SCHEMA_PREFIX@@Timeperiod"],"Attr": "cn"}',
    ),
  ),
  'modules.${moduleName}.searchCategories' => 
  array (
    0 => 
    array (
      'objectclass' => '@@SCHEMA_PREFIX@@Host',
      'category' => 'Host',
      'iconCls' => 'icinga-icon-hostgroup',
    ),
    1 => 
    array (
      'objectclass' => '@@SCHEMA_PREFIX@@Hostgroup',
      'category' => 'Hostgroup',
      'iconCls' => 'icinga-icon-server',
    ),
    2 => 
    array (
      'objectclass' => '@@SCHEMA_PREFIX@@Service',
      'category' => 'Service',
      'iconCls' => 'icinga-icon-cog',
    ),
    3 => 
    array (
      'objectclass' => '@@SCHEMA_PREFIX@@Contact',
      'category' => 'Contact',
      'iconCls' => 'icinga-icon-user',
    ),
    4 => 
    array (
      'objectclass' => '@@SCHEMA_PREFIX@@Contactgroup',
      'category' => 'Contactgroup',
      'iconCls' => 'icinga-icon-group',
    ),
    5 => 
    array (
      'objectclass' => '@@SCHEMA_PREFIX@@Command',
      'category' => 'Command',
      'iconCls' => 'icinga-icon-script',
    ),
    6 => 
    array (
      'objectclass' => '@@SCHEMA_PREFIX@@Timeperiod',
      'category' => 'Contactgroup',
      'iconCls' => 'icinga-icon-clock-red',
    ),
  ),
  'modules.${moduleName}.inheritance' => 
  array (
    '@@SCHEMA_PREFIX@@Service' => 
    array (
      '@@SCHEMA_PREFIX@@Service' => 
      array (
        'attributes' => 
        array (
          '@@SCHEMA_PREFIX@@checkcommand' => 
          array (
            'overwrite' => true,
          ),
        ),
      ),
    ),
    '@@SCHEMA_PREFIX@@Host' => 
    array (
      '@@SCHEMA_PREFIX@@Host' => 
      array (
        'attributes' => 
        array (
          '@@SCHEMA_PREFIX@@address' => 
          array (
            'overwrite' => true,
          ),
          '@@SCHEMA_PREFIX@@alias' => 
          array (
            'overwrite' => true,
          ),
        ),
      ),
    ),
  ),
  'modules.${moduleName}.ldap_definition_ini' => '/usr/local/lconf-standalone/app/modules/LConf/lib/ldapConfig/staticObjects.ini',
  'modules.${moduleName}.ldap_object_presets_ini' => '/usr/local/lconf-standalone/app/modules/LConf/lib/ldapConfig/objectDefaultAttributes.ini',
  'modules.${moduleName}.lconfExport' => 
  array (
    'lconfConsoleInstance' => 'localhost',
  ),
  'modules.${moduleName}.agavi.include.menu' => 
  array (
    0 => '/usr/local/lconf-standalone/app/modules/LConf/config/menu.xml',
  ),
  'modules.${moduleName}.agavi.include.routing' => 
  array (
    0 => '/usr/local/lconf-standalone/app/modules/LConf/config/routing.xml',
  ),
  'modules.${moduleName}.agavi.include.javascript' => 
  array (
    0 => '/usr/local/lconf-standalone/app/modules/LConf/config/javascript.xml',
  ),
  'modules.${moduleName}.agavi.include.css' => 
  array (
    0 => '/usr/local/lconf-standalone/app/modules/LConf/config/css.xml',
  ),
  'modules.${moduleName}.agavi.include.templateExtensions' => 
  array (
    0 => '/usr/local/lconf-standalone/app/modules/LConf/config/templateExtensions/hostServiceGridExtender.xml',
  ),
  'modules.${moduleName}.agavi.include.module' => 
  array (
    0 => '/usr/local/lconf-standalone/app/modules/LConf/config/templateExtensions/hostServiceGridExtender.xml',
  ),
);
$moduleConfigKeys = array_keys($moduleConfig);
foreach($moduleConfigKeys as &$value) $value = AgaviToolkit::expandVariables($value, array('moduleName' => $lcModuleName));
$moduleConfig = array_combine($moduleConfigKeys, $moduleConfig);
AgaviConfig::fromArray($moduleConfig);

?>