<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/AppKit/validate/Admin/PrincipalEditor.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2011-09-02T13:08:04+0000

${'_validator_principal'} = new AgaviNumberValidator();
${'_validator_principal'}->initialize($this->getContext(), array (
  'type' => 'int',
  'severity' => 'error',
  'required' => true,
  'class' => 'number',
  'name' => 'principal',
), array (
  0 => 'principal',
), array (
));
${'validationManager'}->addChild(${'_validator_principal'});
${'_validator_container'} = new AgaviStringValidator();
${'_validator_container'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => false,
  'class' => 'string',
  'name' => 'container',
), array (
  0 => 'container',
), array (
));
${'validationManager'}->addChild(${'_validator_container'});

?>