<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/AppKit/validate/DataProvider/PrincipalProvider.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2011-09-02T13:08:04+0000

${'_validator_userId'} = new AgaviNumberValidator();
${'_validator_userId'}->initialize($this->getContext(), array (
  'type' => 'int',
  'severity' => 'error',
  'required' => false,
  'class' => 'number',
  'name' => 'userId',
), array (
  0 => 'userId',
), array (
  '' => 'Validation of \'userId\' failed',
));
${'validationManager'}->addChild(${'_validator_userId'});
${'_validator_groupId'} = new AgaviNumberValidator();
${'_validator_groupId'}->initialize($this->getContext(), array (
  'type' => 'int',
  'severity' => 'error',
  'required' => false,
  'class' => 'number',
  'name' => 'groupId',
), array (
  0 => 'groupId',
), array (
  '' => 'Validation of \'userId\' failed',
));
${'validationManager'}->addChild(${'_validator_groupId'});

?>