<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/AppKit/validate/Admin/Users/Remove.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2011-09-02T13:02:34+0000

${'_validator_user_id'} = new AgaviNumberValidator();
${'_validator_user_id'}->initialize($this->getContext(), array (
  'type' => 'int',
  'severity' => 'error',
  'required' => true,
  'class' => 'number',
  'name' => 'user_id',
  'base' => 'user_id[]',
), array (
  0 => '',
), array (
));
${'validationManager'}->addChild(${'_validator_user_id'});
${'_validator_disable_only'} = new AgaviIssetValidator();
${'_validator_disable_only'}->initialize($this->getContext(), array (
  'severity' => 'error',
  'required' => false,
  'class' => 'isset',
  'name' => 'disable_only',
), array (
  0 => 'disable_only',
), array (
));
${'validationManager'}->addChild(${'_validator_disable_only'});

?>