<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/config/settings.xml
// Generated by: AgaviSettingConfigHandler
// Date: 2011-09-02T13:02:08+0000

AgaviConfig::fromArray(array (
  'actions.default_module' => 'AppKit',
  'actions.default_action' => 'Index',
  'actions.error_404_module' => 'AppKit',
  'actions.error_404_action' => 'Error404',
  'actions.unavailable_module' => 'AppKit',
  'actions.unavailable_action' => 'Unavailable',
  'actions.module_disabled_module' => 'AppKit',
  'actions.module_disabled_action' => 'ModuleDisabled',
  'actions.secure_module' => 'AppKit',
  'actions.secure_action' => 'Secure',
  'actions.login_module' => 'AppKit',
  'actions.login_action' => 'Login.SilentAuth',
  'core.app_name' => 'LConf',
  'core.available' => true,
  'core.debug' => false,
  'core.use_database' => true,
  'core.use_logging' => true,
  'core.use_security' => true,
  'core.use_translation' => true,
  'core.data_dir' => '/usr/local/lconf-standalone/app/data',
  'core.log_dir' => '%core.data_dir%/log',
  'core.share_dir' => '%core.data_dir%/share',
  'org.icinga.appkit.home_links' => NULL,
  'org.icinga.appkit.web_path' => '/lconf',
  'org.icinga.appkit.log_path' => '/usr/local/lconf-standalone/log',
  'org.icinga.appkit.web_absolute_path' => '/usr/local/lconf-standalone/pub',
  'org.icinga.appkit.logout_path' => '/lconf',
  'org.icinga.appkit.image_path' => '/lconf/images',
  'org.icinga.appkit.image_absolute_path' => '/usr/local/lconf-standalone/pub/images',
  'org.icinga.appkit.include_styles' => NULL,
  'org.icinga.appkit.meta_tags' => NULL,
  'org.icinga.appkit.include_javascript' => NULL,
  'org.icinga.version.copyright' => '&#169; 2009-2011 Icinga Developer Team',
  'org.icinga.version.homeref' => '<a href="http://www.icinga.org/">www.icinga.org</a>',
  'org.icinga.version.major' => '1',
  'org.icinga.version.minor' => '5',
  'org.icinga.version.patch' => '1',
  'org.icinga.version.extension' => NULL,
  'org.icinga.version.releasedate' => '2011-08-26',
  'org.icinga.version.name' => 'icinga-web',
  'exception.default_template' => '/usr/local/lconf-standalone/app/templates/exceptions/web.php',
));

?>