<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/AppKit/validate/Widgets/SquishLoader.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2011-09-02T13:02:12+0000

${'_validator_IfNoneMatch'} = new AgaviStringValidator();
${'_validator_IfNoneMatch'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => false,
  'class' => 'string',
  'name' => 'IfNoneMatch',
  'source' => 'headers',
), array (
  0 => 'IF_NONE_MATCH',
), array (
));
${'validationManager'}->addChild(${'_validator_IfNoneMatch'});

?>