<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/config/translation.xml
// Generated by: AgaviTranslationConfigHandler
// Date: 2011-09-02T13:02:09+0000

$this->defaultDomain = 'icinga.default';
$this->defaultLocaleIdentifier = 'en';
$this->defaultTimeZone = NULL;
$this->availableConfigLocales['de_DE'] = array('identifier' => 'de_DE', 'identifierData' => array (
  'language' => 'de',
  'script' => NULL,
  'territory' => 'DE',
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'de_DE',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Deutsch',
));
$this->availableConfigLocales['en'] = array('identifier' => 'en', 'identifierData' => array (
  'language' => 'en',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'en',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'English',
));
$this->availableConfigLocales['es'] = array('identifier' => 'es', 'identifierData' => array (
  'language' => 'es',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'es',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Español',
));
$this->availableConfigLocales['pl'] = array('identifier' => 'pl', 'identifierData' => array (
  'language' => 'pl',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'pl',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Polski',
));
$this->availableConfigLocales['cs'] = array('identifier' => 'cs', 'identifierData' => array (
  'language' => 'cs',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'cs',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Czech',
));
$this->availableConfigLocales['pt'] = array('identifier' => 'pt', 'identifierData' => array (
  'language' => 'pt',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'pt',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Portugese',
));
$this->availableConfigLocales['pt_BR'] = array('identifier' => 'pt_BR', 'identifierData' => array (
  'language' => 'pt',
  'script' => NULL,
  'territory' => 'BR',
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'pt_BR',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Brazilian Portugese',
));
$this->availableConfigLocales['bg'] = array('identifier' => 'bg', 'identifierData' => array (
  'language' => 'bg',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'bg',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Bulgarian',
));
$this->availableConfigLocales['ca'] = array('identifier' => 'ca', 'identifierData' => array (
  'language' => 'ca',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'ca',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Catalan',
));
$this->availableConfigLocales['da'] = array('identifier' => 'da', 'identifierData' => array (
  'language' => 'da',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'da',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Danish',
));
$this->availableConfigLocales['el'] = array('identifier' => 'el', 'identifierData' => array (
  'language' => 'el',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'el',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Greek',
));
$this->availableConfigLocales['fi'] = array('identifier' => 'fi', 'identifierData' => array (
  'language' => 'fi',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'fi',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Finnish',
));
$this->availableConfigLocales['fr'] = array('identifier' => 'fr', 'identifierData' => array (
  'language' => 'fr',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'fr',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'French',
));
$this->availableConfigLocales['he'] = array('identifier' => 'he', 'identifierData' => array (
  'language' => 'he',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'he',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Hebrew',
));
$this->availableConfigLocales['hr'] = array('identifier' => 'hr', 'identifierData' => array (
  'language' => 'hr',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'hr',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Croatian',
));
$this->availableConfigLocales['hu'] = array('identifier' => 'hu', 'identifierData' => array (
  'language' => 'hu',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'hu',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Hungarian',
));
$this->availableConfigLocales['it'] = array('identifier' => 'it', 'identifierData' => array (
  'language' => 'it',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'it',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Italian',
));
$this->availableConfigLocales['ja'] = array('identifier' => 'ja', 'identifierData' => array (
  'language' => 'ja',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'ja',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Japanese',
));
$this->availableConfigLocales['lb'] = array('identifier' => 'lb', 'identifierData' => array (
  'language' => 'lb',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'lb',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Luxembourgish',
));
$this->availableConfigLocales['nb'] = array('identifier' => 'nb', 'identifierData' => array (
  'language' => 'nb',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'nb',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Bokmål',
));
$this->availableConfigLocales['nl'] = array('identifier' => 'nl', 'identifierData' => array (
  'language' => 'nl',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'nl',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Dutch',
));
$this->availableConfigLocales['nn'] = array('identifier' => 'nn', 'identifierData' => array (
  'language' => 'nn',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'nn',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Norwegian',
));
$this->availableConfigLocales['ro'] = array('identifier' => 'ro', 'identifierData' => array (
  'language' => 'ro',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'ro',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Romanian',
));
$this->availableConfigLocales['ru'] = array('identifier' => 'ru', 'identifierData' => array (
  'language' => 'ru',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'ru',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Russian',
));
$this->availableConfigLocales['sk'] = array('identifier' => 'sk', 'identifierData' => array (
  'language' => 'sk',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'sk',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Slovak',
));
$this->availableConfigLocales['sv'] = array('identifier' => 'sv', 'identifierData' => array (
  'language' => 'sv',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'sv',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Swedish',
));
$this->availableConfigLocales['tr'] = array('identifier' => 'tr', 'identifierData' => array (
  'language' => 'tr',
  'script' => NULL,
  'territory' => NULL,
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'tr',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Turkish',
));
$this->availableConfigLocales['zh_CN'] = array('identifier' => 'zh_CN', 'identifierData' => array (
  'language' => 'zh',
  'script' => NULL,
  'territory' => 'CN',
  'variant' => NULL,
  'options' => 
  array (
  ),
  'locale_str' => 'zh_CN',
  'option_str' => NULL,
), 'parameters' => array (
  'description' => 'Chinese',
));
$this->translators['icinga']['msg'] = new AppKitGettextTranslator();
$this->translators['icinga']['msg']->initialize($this->getContext(), array (
  'text_domains' => 
  array (
    'default' => '/usr/local/lconf-standalone/app/data/i18n/mo',
  ),
  'text_domain_pattern' => '/usr/local/lconf-standalone/app/modules/${domain}/data/i18n/mo',
));
$this->translatorFilters['icinga']['msg'] = array (
);
$this->translators['icinga']['num'] = new AgaviNumberFormatter();
$this->translators['icinga']['num']->initialize($this->getContext(), array (
));
$this->translatorFilters['icinga']['num'] = array (
);
$this->translators['icinga']['cur'] = new AgaviCurrencyFormatter();
$this->translators['icinga']['cur']->initialize($this->getContext(), array (
));
$this->translatorFilters['icinga']['cur'] = array (
);
$this->translators['icinga']['date'] = new AgaviDateFormatter();
$this->translators['icinga']['date']->initialize($this->getContext(), array (
  'type' => 'date',
  'format' => 'full',
));
$this->translatorFilters['icinga']['date'] = array (
);
$this->translators['date-short']['num'] = new AgaviNumberFormatter();
$this->translators['date-short']['num']->initialize($this->getContext(), array (
));
$this->translatorFilters['date-short']['num'] = array (
);
$this->translators['date-short']['cur'] = new AgaviCurrencyFormatter();
$this->translators['date-short']['cur']->initialize($this->getContext(), array (
));
$this->translatorFilters['date-short']['cur'] = array (
);
$this->translators['date-short']['date'] = new AgaviDateFormatter();
$this->translators['date-short']['date']->initialize($this->getContext(), array (
  'type' => 'date',
  'format' => 'short',
));
$this->translatorFilters['date-short']['date'] = array (
);
$this->translators['date-medium']['num'] = new AgaviNumberFormatter();
$this->translators['date-medium']['num']->initialize($this->getContext(), array (
));
$this->translatorFilters['date-medium']['num'] = array (
);
$this->translators['date-medium']['cur'] = new AgaviCurrencyFormatter();
$this->translators['date-medium']['cur']->initialize($this->getContext(), array (
));
$this->translatorFilters['date-medium']['cur'] = array (
);
$this->translators['date-medium']['date'] = new AgaviDateFormatter();
$this->translators['date-medium']['date']->initialize($this->getContext(), array (
  'type' => 'date',
  'format' => 'medium',
));
$this->translatorFilters['date-medium']['date'] = array (
);
$this->translators['date-tstamp']['num'] = new AgaviNumberFormatter();
$this->translators['date-tstamp']['num']->initialize($this->getContext(), array (
));
$this->translatorFilters['date-tstamp']['num'] = array (
);
$this->translators['date-tstamp']['cur'] = new AgaviCurrencyFormatter();
$this->translators['date-tstamp']['cur']->initialize($this->getContext(), array (
));
$this->translatorFilters['date-tstamp']['cur'] = array (
);
$this->translators['date-tstamp']['date'] = new AgaviDateFormatter();
$this->translators['date-tstamp']['date']->initialize($this->getContext(), array (
  'type' => 'date',
  'format' => 'yyyy-MM-dd HH:mm:ss',
));
$this->translatorFilters['date-tstamp']['date'] = array (
);

?>