<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/AppKit/validate/DataProvider/UserProvider.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2011-09-02T13:02:26+0000

${'_validator_userId'} = new AgaviNumberValidator();
${'_validator_userId'}->initialize($this->getContext(), array (
  'type' => 'int',
  'severity' => 'error',
  'required' => false,
  'class' => 'number',
  'name' => 'userId',
), array (
  0 => 'userId',
), array (
  '' => 'Validation of \'userId\' failed',
));
${'validationManager'}->addChild(${'_validator_userId'});
${'_validator_hideDisabled'} = new AgaviStringValidator();
${'_validator_hideDisabled'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => false,
  'class' => 'string',
  'name' => 'hideDisabled',
), array (
  0 => 'hideDisabled',
), array (
));
${'validationManager'}->addChild(${'_validator_hideDisabled'});
${'_validator_start'} = new AgaviNumberValidator();
${'_validator_start'}->initialize($this->getContext(), array (
  'type' => 'int',
  'severity' => 'error',
  'required' => false,
  'class' => 'number',
  'name' => 'start',
), array (
  0 => 'start',
), array (
));
${'validationManager'}->addChild(${'_validator_start'});
${'_validator_limit'} = new AgaviNumberValidator();
${'_validator_limit'}->initialize($this->getContext(), array (
  'type' => 'int',
  'severity' => 'error',
  'required' => false,
  'class' => 'number',
  'name' => 'limit',
), array (
  0 => 'limit',
), array (
));
${'validationManager'}->addChild(${'_validator_limit'});
${'_validator_sort'} = new AgaviStringValidator();
${'_validator_sort'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => false,
  'class' => 'string',
  'name' => 'sort',
), array (
  0 => 'sort',
), array (
));
${'validationManager'}->addChild(${'_validator_sort'});
${'_validator_dir'} = new AgaviStringValidator();
${'_validator_dir'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => false,
  'class' => 'string',
  'name' => 'dir',
), array (
  0 => 'dir',
), array (
));
${'validationManager'}->addChild(${'_validator_dir'});

?>