<?php

// This is a compiled Agavi configuration file
// Compiled from: /usr/local/lconf-standalone/app/modules/LConf/validate/Interface/ViewMainEditor.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2011-09-02T13:02:10+0000

${'_validator_connection'} = new AgaviStringValidator();
${'_validator_connection'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => false,
  'class' => 'string',
  'name' => 'connection',
), array (
  0 => 'connection',
), array (
  '' => 'Validation of \'connection\' failed',
));
${'validationManager'}->addChild(${'_validator_connection'});
${'_validator_dn'} = new AgaviStringValidator();
${'_validator_dn'}->initialize($this->getContext(), array (
  'min' => '1',
  'severity' => 'error',
  'required' => false,
  'class' => 'string',
  'name' => 'dn',
), array (
  0 => 'dn',
), array (
  '' => 'Validation of \'dn\' failed',
));
${'validationManager'}->addChild(${'_validator_dn'});

?>